//// Auto-generated by scripts/emit-dispatchers.py for awsjson11.
//// DO NOT EDIT manually — re-run the script after regenerating the
//// service module.

import aws/services/protocoltests/json11 as svc
import protocol_tests/dispatch.{
  type Dispatcher, type ParsedResponseInput, type Registry, BuiltRequest,
  Dispatcher, ParsedOutput,
}

pub fn register_all(registry: Registry) -> Registry {
  registry
  |> dispatch.register(empty_operation_dispatcher())
  |> dispatch.register(endpoint_operation_dispatcher())
  |> dispatch.register(host_with_path_operation_dispatcher())
  |> dispatch.register(null_operation_dispatcher())
  |> dispatch.register(operation_with_optional_input_output_dispatcher())
  |> dispatch.register(simple_scalar_properties_dispatcher())
}

fn empty_operation_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.json#EmptyOperation",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_empty_operation_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_empty_operation_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_empty_operation_response),
  )
}

fn endpoint_operation_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.json#EndpointOperation",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_endpoint_operation_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_endpoint_operation_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_endpoint_operation_response),
  )
}

fn host_with_path_operation_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.json#HostWithPathOperation",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_host_with_path_operation_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_host_with_path_operation_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_host_with_path_operation_response),
  )
}

fn null_operation_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.json#NullOperation",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_null_operation_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_null_operation_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_null_operation_response),
  )
}

fn operation_with_optional_input_output_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.json#OperationWithOptionalInputOutput",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_operation_with_optional_input_output_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_operation_with_optional_input_output_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_operation_with_optional_input_output_response,
    ),
  )
}

fn simple_scalar_properties_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.json#SimpleScalarProperties",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_simple_scalar_properties_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_simple_scalar_properties_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_simple_scalar_properties_response),
  )
}

fn response_parser(
  parser: fn(Int, _, BitArray) -> Result(_, String),
) -> fn(ParsedResponseInput) -> Result(dispatch.ParsedResponse, String) {
  fn(input: ParsedResponseInput) {
    case parser(input.code, input.headers, input.body) {
      Ok(_) -> Ok(ParsedOutput(json: "{}"))
      Error(e) -> Error(e)
    }
  }
}
