//// Auto-generated by scripts/emit-dispatchers.py for awsjson10.
//// DO NOT EDIT manually — re-run the script after regenerating the
//// service module.

import aws/services/protocoltests/json10 as svc
import protocol_tests/dispatch.{
  type Dispatcher, type ParsedResponseInput, type Registry, BuiltRequest,
  Dispatcher, ParsedOutput,
}

pub fn register_all(registry: Registry) -> Registry {
  registry
  |> dispatch.register(empty_input_and_empty_output_dispatcher())
  |> dispatch.register(endpoint_operation_dispatcher())
  |> dispatch.register(host_with_path_operation_dispatcher())
  |> dispatch.register(no_input_and_no_output_dispatcher())
  |> dispatch.register(no_input_and_output_dispatcher())
  |> dispatch.register(query_incompatible_operation_dispatcher())
}

fn empty_input_and_empty_output_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.json10#EmptyInputAndEmptyOutput",
    build_request: fn(_params) {
      let #(method, uri, headers, body) =
        svc.build_empty_input_and_empty_output_request(
          svc.EmptyInputAndEmptyOutputInput,
        )
      Ok(BuiltRequest(method: method, uri: uri, headers: headers, body: body))
    },
    parse_response: empty_response_parser(
      svc.parse_empty_input_and_empty_output_response,
    ),
  )
}

fn endpoint_operation_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.json10#EndpointOperation",
    build_request: fn(_params) {
      let #(method, uri, headers, body) =
        svc.build_endpoint_operation_request(svc.EndpointOperationInput)
      Ok(BuiltRequest(method: method, uri: uri, headers: headers, body: body))
    },
    parse_response: empty_response_parser(svc.parse_endpoint_operation_response),
  )
}

fn host_with_path_operation_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.json10#HostWithPathOperation",
    build_request: fn(_params) {
      let #(method, uri, headers, body) =
        svc.build_host_with_path_operation_request(
          svc.HostWithPathOperationInput,
        )
      Ok(BuiltRequest(method: method, uri: uri, headers: headers, body: body))
    },
    parse_response: empty_response_parser(
      svc.parse_host_with_path_operation_response,
    ),
  )
}

fn no_input_and_no_output_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.json10#NoInputAndNoOutput",
    build_request: fn(_params) {
      let #(method, uri, headers, body) =
        svc.build_no_input_and_no_output_request(svc.NoInputAndNoOutputInput)
      Ok(BuiltRequest(method: method, uri: uri, headers: headers, body: body))
    },
    parse_response: empty_response_parser(
      svc.parse_no_input_and_no_output_response,
    ),
  )
}

fn no_input_and_output_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.json10#NoInputAndOutput",
    build_request: fn(_params) {
      let #(method, uri, headers, body) =
        svc.build_no_input_and_output_request(svc.NoInputAndOutputInput)
      Ok(BuiltRequest(method: method, uri: uri, headers: headers, body: body))
    },
    parse_response: empty_response_parser(
      svc.parse_no_input_and_output_response,
    ),
  )
}

fn query_incompatible_operation_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.json10#QueryIncompatibleOperation",
    build_request: fn(_params) {
      let #(method, uri, headers, body) =
        svc.build_query_incompatible_operation_request(
          svc.QueryIncompatibleOperationInput,
        )
      Ok(BuiltRequest(method: method, uri: uri, headers: headers, body: body))
    },
    parse_response: empty_response_parser(
      svc.parse_query_incompatible_operation_response,
    ),
  )
}

fn empty_response_parser(
  parser: fn(Int, _, BitArray) -> Result(_, String),
) -> fn(ParsedResponseInput) -> Result(dispatch.ParsedResponse, String) {
  fn(input: ParsedResponseInput) {
    case parser(input.code, input.headers, input.body) {
      Ok(_) -> Ok(ParsedOutput(json: "{}"))
      Error(e) -> Error(e)
    }
  }
}
