//// Auto-generated by codegen/dispatcher.gleam for ec2query.
//// DO NOT EDIT manually — re-run `./scripts/regen.sh` after
//// regenerating the service module.

import aws/services/protocoltests/ec2query as svc
import protocol_tests/dispatch.{
  type Dispatcher, type ParsedResponseInput, type Registry, BuiltRequest,
  Dispatcher, ParsedOutput,
}

pub fn register_all(registry: Registry) -> Registry {
  registry
  |> dispatch.register(datetime_offsets_dispatcher())
  |> dispatch.register(empty_input_and_empty_output_dispatcher())
  |> dispatch.register(endpoint_operation_dispatcher())
  |> dispatch.register(endpoint_with_host_label_operation_dispatcher())
  |> dispatch.register(fractional_seconds_dispatcher())
  |> dispatch.register(greeting_with_errors_dispatcher())
  |> dispatch.register(host_with_path_operation_dispatcher())
  |> dispatch.register(ignores_wrapping_xml_name_dispatcher())
  |> dispatch.register(nested_structures_dispatcher())
  |> dispatch.register(no_input_and_output_dispatcher())
  |> dispatch.register(query_idempotency_token_auto_fill_dispatcher())
  |> dispatch.register(query_lists_dispatcher())
  |> dispatch.register(query_timestamps_dispatcher())
  |> dispatch.register(recursive_xml_shapes_dispatcher())
  |> dispatch.register(simple_input_params_dispatcher())
  |> dispatch.register(simple_scalar_xml_properties_dispatcher())
  |> dispatch.register(xml_blobs_dispatcher())
  |> dispatch.register(xml_empty_blobs_dispatcher())
  |> dispatch.register(xml_empty_lists_dispatcher())
  |> dispatch.register(xml_enums_dispatcher())
  |> dispatch.register(xml_int_enums_dispatcher())
  |> dispatch.register(xml_lists_dispatcher())
  |> dispatch.register(xml_namespaces_dispatcher())
  |> dispatch.register(xml_timestamps_dispatcher())
  |> dispatch.register(complex_error_dispatcher())
  |> dispatch.register(invalid_greeting_dispatcher())
}

fn datetime_offsets_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.ec2#DatetimeOffsets",
    build_request: fn(params) {
      let _ = params
      let #(method, uri, headers, body) =
        svc.build_datetime_offsets_request(svc.DatetimeOffsetsInput)
      Ok(BuiltRequest(method:, uri:, headers:, body:))
    },
    parse_response: response_parser(svc.parse_datetime_offsets_response),
  )
}

fn empty_input_and_empty_output_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.ec2#EmptyInputAndEmptyOutput",
    build_request: fn(params) {
      let _ = params
      let #(method, uri, headers, body) =
        svc.build_empty_input_and_empty_output_request(
          svc.EmptyInputAndEmptyOutputInput,
        )
      Ok(BuiltRequest(method:, uri:, headers:, body:))
    },
    parse_response: response_parser(
      svc.parse_empty_input_and_empty_output_response,
    ),
  )
}

fn endpoint_operation_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.ec2#EndpointOperation",
    build_request: fn(params) {
      let _ = params
      let #(method, uri, headers, body) =
        svc.build_endpoint_operation_request(svc.EndpointOperationInput)
      Ok(BuiltRequest(method:, uri:, headers:, body:))
    },
    parse_response: response_parser(svc.parse_endpoint_operation_response),
  )
}

fn endpoint_with_host_label_operation_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.ec2#EndpointWithHostLabelOperation",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_endpoint_with_host_label_operation_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_endpoint_with_host_label_operation_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_endpoint_with_host_label_operation_response,
    ),
  )
}

fn fractional_seconds_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.ec2#FractionalSeconds",
    build_request: fn(params) {
      let _ = params
      let #(method, uri, headers, body) =
        svc.build_fractional_seconds_request(svc.FractionalSecondsInput)
      Ok(BuiltRequest(method:, uri:, headers:, body:))
    },
    parse_response: response_parser(svc.parse_fractional_seconds_response),
  )
}

fn greeting_with_errors_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.ec2#GreetingWithErrors",
    build_request: fn(params) {
      let _ = params
      let #(method, uri, headers, body) =
        svc.build_greeting_with_errors_request(svc.GreetingWithErrorsInput)
      Ok(BuiltRequest(method:, uri:, headers:, body:))
    },
    parse_response: response_parser(svc.parse_greeting_with_errors_response),
  )
}

fn host_with_path_operation_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.ec2#HostWithPathOperation",
    build_request: fn(params) {
      let _ = params
      let #(method, uri, headers, body) =
        svc.build_host_with_path_operation_request(
          svc.HostWithPathOperationInput,
        )
      Ok(BuiltRequest(method:, uri:, headers:, body:))
    },
    parse_response: response_parser(svc.parse_host_with_path_operation_response),
  )
}

fn ignores_wrapping_xml_name_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.ec2#IgnoresWrappingXmlName",
    build_request: fn(params) {
      let _ = params
      let #(method, uri, headers, body) =
        svc.build_ignores_wrapping_xml_name_request(
          svc.IgnoresWrappingXmlNameInput,
        )
      Ok(BuiltRequest(method:, uri:, headers:, body:))
    },
    parse_response: response_parser(
      svc.parse_ignores_wrapping_xml_name_response,
    ),
  )
}

fn nested_structures_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.ec2#NestedStructures",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_nested_structures_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_nested_structures_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_nested_structures_response),
  )
}

fn no_input_and_output_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.ec2#NoInputAndOutput",
    build_request: fn(params) {
      let _ = params
      let #(method, uri, headers, body) =
        svc.build_no_input_and_output_request(svc.NoInputAndOutputInput)
      Ok(BuiltRequest(method:, uri:, headers:, body:))
    },
    parse_response: response_parser(svc.parse_no_input_and_output_response),
  )
}

fn query_idempotency_token_auto_fill_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.ec2#QueryIdempotencyTokenAutoFill",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_query_idempotency_token_auto_fill_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_query_idempotency_token_auto_fill_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_query_idempotency_token_auto_fill_response,
    ),
  )
}

fn query_lists_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.ec2#QueryLists",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_query_lists_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_query_lists_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_query_lists_response),
  )
}

fn query_timestamps_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.ec2#QueryTimestamps",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_query_timestamps_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_query_timestamps_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_query_timestamps_response),
  )
}

fn recursive_xml_shapes_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.ec2#RecursiveXmlShapes",
    build_request: fn(params) {
      let _ = params
      let #(method, uri, headers, body) =
        svc.build_recursive_xml_shapes_request(svc.RecursiveXmlShapesInput)
      Ok(BuiltRequest(method:, uri:, headers:, body:))
    },
    parse_response: response_parser(svc.parse_recursive_xml_shapes_response),
  )
}

fn simple_input_params_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.ec2#SimpleInputParams",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_simple_input_params_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_simple_input_params_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_simple_input_params_response),
  )
}

fn simple_scalar_xml_properties_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.ec2#SimpleScalarXmlProperties",
    build_request: fn(params) {
      let _ = params
      let #(method, uri, headers, body) =
        svc.build_simple_scalar_xml_properties_request(
          svc.SimpleScalarXmlPropertiesInput,
        )
      Ok(BuiltRequest(method:, uri:, headers:, body:))
    },
    parse_response: response_parser(
      svc.parse_simple_scalar_xml_properties_response,
    ),
  )
}

fn xml_blobs_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.ec2#XmlBlobs",
    build_request: fn(params) {
      let _ = params
      let #(method, uri, headers, body) =
        svc.build_xml_blobs_request(svc.XmlBlobsInput)
      Ok(BuiltRequest(method:, uri:, headers:, body:))
    },
    parse_response: response_parser(svc.parse_xml_blobs_response),
  )
}

fn xml_empty_blobs_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.ec2#XmlEmptyBlobs",
    build_request: fn(params) {
      let _ = params
      let #(method, uri, headers, body) =
        svc.build_xml_empty_blobs_request(svc.XmlEmptyBlobsInput)
      Ok(BuiltRequest(method:, uri:, headers:, body:))
    },
    parse_response: response_parser(svc.parse_xml_empty_blobs_response),
  )
}

fn xml_empty_lists_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.ec2#XmlEmptyLists",
    build_request: fn(params) {
      let _ = params
      let #(method, uri, headers, body) =
        svc.build_xml_empty_lists_request(svc.XmlEmptyListsInput)
      Ok(BuiltRequest(method:, uri:, headers:, body:))
    },
    parse_response: response_parser(svc.parse_xml_empty_lists_response),
  )
}

fn xml_enums_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.ec2#XmlEnums",
    build_request: fn(params) {
      let _ = params
      let #(method, uri, headers, body) =
        svc.build_xml_enums_request(svc.XmlEnumsInput)
      Ok(BuiltRequest(method:, uri:, headers:, body:))
    },
    parse_response: response_parser(svc.parse_xml_enums_response),
  )
}

fn xml_int_enums_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.ec2#XmlIntEnums",
    build_request: fn(params) {
      let _ = params
      let #(method, uri, headers, body) =
        svc.build_xml_int_enums_request(svc.XmlIntEnumsInput)
      Ok(BuiltRequest(method:, uri:, headers:, body:))
    },
    parse_response: response_parser(svc.parse_xml_int_enums_response),
  )
}

fn xml_lists_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.ec2#XmlLists",
    build_request: fn(params) {
      let _ = params
      let #(method, uri, headers, body) =
        svc.build_xml_lists_request(svc.XmlListsInput)
      Ok(BuiltRequest(method:, uri:, headers:, body:))
    },
    parse_response: response_parser(svc.parse_xml_lists_response),
  )
}

fn xml_namespaces_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.ec2#XmlNamespaces",
    build_request: fn(params) {
      let _ = params
      let #(method, uri, headers, body) =
        svc.build_xml_namespaces_request(svc.XmlNamespacesInput)
      Ok(BuiltRequest(method:, uri:, headers:, body:))
    },
    parse_response: response_parser(svc.parse_xml_namespaces_response),
  )
}

fn xml_timestamps_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.ec2#XmlTimestamps",
    build_request: fn(params) {
      let _ = params
      let #(method, uri, headers, body) =
        svc.build_xml_timestamps_request(svc.XmlTimestampsInput)
      Ok(BuiltRequest(method:, uri:, headers:, body:))
    },
    parse_response: response_parser(svc.parse_xml_timestamps_response),
  )
}

fn complex_error_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.ec2#ComplexError",
    build_request: fn(_params) {
      Error("error-shape dispatcher has no request side")
    },
    parse_response: response_parser(svc.parse_complex_error_response),
  )
}

fn invalid_greeting_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.ec2#InvalidGreeting",
    build_request: fn(_params) {
      Error("error-shape dispatcher has no request side")
    },
    parse_response: response_parser(svc.parse_invalid_greeting_response),
  )
}

fn response_parser(
  parser: fn(Int, _, BitArray) -> Result(_, String),
) -> fn(ParsedResponseInput) -> Result(dispatch.ParsedResponse, String) {
  fn(input: ParsedResponseInput) {
    case parser(input.code, input.headers, input.body) {
      Ok(_) -> Ok(ParsedOutput(json: "{}"))
      Error(e) -> Error(e)
    }
  }
}
