//// Auto-generated by codegen/dispatcher.gleam for restxml_with_namespace.
//// DO NOT EDIT manually — re-run `./scripts/regen.sh` after
//// regenerating the service module.

import aws/services/protocoltests/restxml_with_namespace as svc
import protocol_tests/dispatch.{
  type Dispatcher, type ParsedResponseInput, type Registry, BuiltRequest,
  Dispatcher, ParsedOutput,
}

pub fn register_all(registry: Registry) -> Registry {
  registry
  |> dispatch.register(simple_scalar_properties_dispatcher())
}

fn simple_scalar_properties_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml.xmlns#SimpleScalarProperties",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_simple_scalar_properties_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_simple_scalar_properties_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_simple_scalar_properties_response),
  )
}

fn response_parser(
  parser: fn(Int, _, BitArray) -> Result(_, String),
) -> fn(ParsedResponseInput) -> Result(dispatch.ParsedResponse, String) {
  fn(input: ParsedResponseInput) {
    case parser(input.code, input.headers, input.body) {
      Ok(_) -> Ok(ParsedOutput(json: "{}"))
      Error(e) -> Error(e)
    }
  }
}
