//// Auto-generated by scripts/emit-dispatchers.py for restjson1.
//// DO NOT EDIT manually — re-run the script after regenerating the
//// service module.

import aws/services/protocoltests/restjson1 as svc
import protocol_tests/dispatch.{
  type Dispatcher, type ParsedResponseInput, type Registry, BuiltRequest,
  Dispatcher, ParsedOutput,
}

pub fn register_all(registry: Registry) -> Registry {
  registry
  |> dispatch.register(datetime_offsets_dispatcher())
  |> dispatch.register(empty_input_and_empty_output_dispatcher())
  |> dispatch.register(endpoint_operation_dispatcher())
  |> dispatch.register(fractional_seconds_dispatcher())
  |> dispatch.register(greeting_with_errors_dispatcher())
  |> dispatch.register(host_with_path_operation_dispatcher())
  |> dispatch.register(http_prefix_headers_in_response_dispatcher())
  |> dispatch.register(http_response_code_dispatcher())
  |> dispatch.register(ignore_query_params_in_response_dispatcher())
  |> dispatch.register(malformed_accept_with_body_dispatcher())
  |> dispatch.register(malformed_accept_with_generic_string_dispatcher())
  |> dispatch.register(malformed_accept_with_payload_dispatcher())
  |> dispatch.register(malformed_content_type_without_body_dispatcher())
  |> dispatch.register(no_input_and_no_output_dispatcher())
  |> dispatch.register(no_input_and_output_dispatcher())
  |> dispatch.register(output_stream_dispatcher())
  |> dispatch.register(output_stream_with_initial_response_dispatcher())
  |> dispatch.register(response_code_http_fallback_dispatcher())
  |> dispatch.register(response_code_required_dispatcher())
  |> dispatch.register(test_get_no_input_no_payload_dispatcher())
  |> dispatch.register(test_post_no_input_no_payload_dispatcher())
  |> dispatch.register(unit_input_and_output_dispatcher())
}

fn datetime_offsets_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#DatetimeOffsets",
    build_request: fn(_params) {
      let #(method, uri, headers, body) =
        svc.build_datetime_offsets_request(svc.DatetimeOffsetsInput)
      Ok(BuiltRequest(method: method, uri: uri, headers: headers, body: body))
    },
    parse_response: empty_response_parser(svc.parse_datetime_offsets_response),
  )
}

fn empty_input_and_empty_output_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#EmptyInputAndEmptyOutput",
    build_request: fn(_params) {
      let #(method, uri, headers, body) =
        svc.build_empty_input_and_empty_output_request(
          svc.EmptyInputAndEmptyOutputInput,
        )
      Ok(BuiltRequest(method: method, uri: uri, headers: headers, body: body))
    },
    parse_response: empty_response_parser(
      svc.parse_empty_input_and_empty_output_response,
    ),
  )
}

fn endpoint_operation_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#EndpointOperation",
    build_request: fn(_params) {
      let #(method, uri, headers, body) =
        svc.build_endpoint_operation_request(svc.EndpointOperationInput)
      Ok(BuiltRequest(method: method, uri: uri, headers: headers, body: body))
    },
    parse_response: empty_response_parser(svc.parse_endpoint_operation_response),
  )
}

fn fractional_seconds_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#FractionalSeconds",
    build_request: fn(_params) {
      let #(method, uri, headers, body) =
        svc.build_fractional_seconds_request(svc.FractionalSecondsInput)
      Ok(BuiltRequest(method: method, uri: uri, headers: headers, body: body))
    },
    parse_response: empty_response_parser(svc.parse_fractional_seconds_response),
  )
}

fn greeting_with_errors_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#GreetingWithErrors",
    build_request: fn(_params) {
      let #(method, uri, headers, body) =
        svc.build_greeting_with_errors_request(svc.GreetingWithErrorsInput)
      Ok(BuiltRequest(method: method, uri: uri, headers: headers, body: body))
    },
    parse_response: empty_response_parser(
      svc.parse_greeting_with_errors_response,
    ),
  )
}

fn host_with_path_operation_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#HostWithPathOperation",
    build_request: fn(_params) {
      let #(method, uri, headers, body) =
        svc.build_host_with_path_operation_request(
          svc.HostWithPathOperationInput,
        )
      Ok(BuiltRequest(method: method, uri: uri, headers: headers, body: body))
    },
    parse_response: empty_response_parser(
      svc.parse_host_with_path_operation_response,
    ),
  )
}

fn http_prefix_headers_in_response_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#HttpPrefixHeadersInResponse",
    build_request: fn(_params) {
      let #(method, uri, headers, body) =
        svc.build_http_prefix_headers_in_response_request(
          svc.HttpPrefixHeadersInResponseInput,
        )
      Ok(BuiltRequest(method: method, uri: uri, headers: headers, body: body))
    },
    parse_response: empty_response_parser(
      svc.parse_http_prefix_headers_in_response_response,
    ),
  )
}

fn http_response_code_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#HttpResponseCode",
    build_request: fn(_params) {
      let #(method, uri, headers, body) =
        svc.build_http_response_code_request(svc.HttpResponseCodeInput)
      Ok(BuiltRequest(method: method, uri: uri, headers: headers, body: body))
    },
    parse_response: empty_response_parser(svc.parse_http_response_code_response),
  )
}

fn ignore_query_params_in_response_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#IgnoreQueryParamsInResponse",
    build_request: fn(_params) {
      let #(method, uri, headers, body) =
        svc.build_ignore_query_params_in_response_request(
          svc.IgnoreQueryParamsInResponseInput,
        )
      Ok(BuiltRequest(method: method, uri: uri, headers: headers, body: body))
    },
    parse_response: empty_response_parser(
      svc.parse_ignore_query_params_in_response_response,
    ),
  )
}

fn malformed_accept_with_body_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#MalformedAcceptWithBody",
    build_request: fn(_params) {
      let #(method, uri, headers, body) =
        svc.build_malformed_accept_with_body_request(
          svc.MalformedAcceptWithBodyInput,
        )
      Ok(BuiltRequest(method: method, uri: uri, headers: headers, body: body))
    },
    parse_response: empty_response_parser(
      svc.parse_malformed_accept_with_body_response,
    ),
  )
}

fn malformed_accept_with_generic_string_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#MalformedAcceptWithGenericString",
    build_request: fn(_params) {
      let #(method, uri, headers, body) =
        svc.build_malformed_accept_with_generic_string_request(
          svc.MalformedAcceptWithGenericStringInput,
        )
      Ok(BuiltRequest(method: method, uri: uri, headers: headers, body: body))
    },
    parse_response: empty_response_parser(
      svc.parse_malformed_accept_with_generic_string_response,
    ),
  )
}

fn malformed_accept_with_payload_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#MalformedAcceptWithPayload",
    build_request: fn(_params) {
      let #(method, uri, headers, body) =
        svc.build_malformed_accept_with_payload_request(
          svc.MalformedAcceptWithPayloadInput,
        )
      Ok(BuiltRequest(method: method, uri: uri, headers: headers, body: body))
    },
    parse_response: empty_response_parser(
      svc.parse_malformed_accept_with_payload_response,
    ),
  )
}

fn malformed_content_type_without_body_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#MalformedContentTypeWithoutBody",
    build_request: fn(_params) {
      let #(method, uri, headers, body) =
        svc.build_malformed_content_type_without_body_request(
          svc.MalformedContentTypeWithoutBodyInput,
        )
      Ok(BuiltRequest(method: method, uri: uri, headers: headers, body: body))
    },
    parse_response: empty_response_parser(
      svc.parse_malformed_content_type_without_body_response,
    ),
  )
}

fn no_input_and_no_output_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#NoInputAndNoOutput",
    build_request: fn(_params) {
      let #(method, uri, headers, body) =
        svc.build_no_input_and_no_output_request(svc.NoInputAndNoOutputInput)
      Ok(BuiltRequest(method: method, uri: uri, headers: headers, body: body))
    },
    parse_response: empty_response_parser(
      svc.parse_no_input_and_no_output_response,
    ),
  )
}

fn no_input_and_output_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#NoInputAndOutput",
    build_request: fn(_params) {
      let #(method, uri, headers, body) =
        svc.build_no_input_and_output_request(svc.NoInputAndOutputInput)
      Ok(BuiltRequest(method: method, uri: uri, headers: headers, body: body))
    },
    parse_response: empty_response_parser(
      svc.parse_no_input_and_output_response,
    ),
  )
}

fn output_stream_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#OutputStream",
    build_request: fn(_params) {
      let #(method, uri, headers, body) =
        svc.build_output_stream_request(svc.OutputStreamInput)
      Ok(BuiltRequest(method: method, uri: uri, headers: headers, body: body))
    },
    parse_response: empty_response_parser(svc.parse_output_stream_response),
  )
}

fn output_stream_with_initial_response_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#OutputStreamWithInitialResponse",
    build_request: fn(_params) {
      let #(method, uri, headers, body) =
        svc.build_output_stream_with_initial_response_request(
          svc.OutputStreamWithInitialResponseInput,
        )
      Ok(BuiltRequest(method: method, uri: uri, headers: headers, body: body))
    },
    parse_response: empty_response_parser(
      svc.parse_output_stream_with_initial_response_response,
    ),
  )
}

fn response_code_http_fallback_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#ResponseCodeHttpFallback",
    build_request: fn(_params) {
      let #(method, uri, headers, body) =
        svc.build_response_code_http_fallback_request(
          svc.ResponseCodeHttpFallbackInput,
        )
      Ok(BuiltRequest(method: method, uri: uri, headers: headers, body: body))
    },
    parse_response: empty_response_parser(
      svc.parse_response_code_http_fallback_response,
    ),
  )
}

fn response_code_required_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#ResponseCodeRequired",
    build_request: fn(_params) {
      let #(method, uri, headers, body) =
        svc.build_response_code_required_request(svc.ResponseCodeRequiredInput)
      Ok(BuiltRequest(method: method, uri: uri, headers: headers, body: body))
    },
    parse_response: empty_response_parser(
      svc.parse_response_code_required_response,
    ),
  )
}

fn test_get_no_input_no_payload_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#TestGetNoInputNoPayload",
    build_request: fn(_params) {
      let #(method, uri, headers, body) =
        svc.build_test_get_no_input_no_payload_request(
          svc.TestGetNoInputNoPayloadInput,
        )
      Ok(BuiltRequest(method: method, uri: uri, headers: headers, body: body))
    },
    parse_response: empty_response_parser(
      svc.parse_test_get_no_input_no_payload_response,
    ),
  )
}

fn test_post_no_input_no_payload_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#TestPostNoInputNoPayload",
    build_request: fn(_params) {
      let #(method, uri, headers, body) =
        svc.build_test_post_no_input_no_payload_request(
          svc.TestPostNoInputNoPayloadInput,
        )
      Ok(BuiltRequest(method: method, uri: uri, headers: headers, body: body))
    },
    parse_response: empty_response_parser(
      svc.parse_test_post_no_input_no_payload_response,
    ),
  )
}

fn unit_input_and_output_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#UnitInputAndOutput",
    build_request: fn(_params) {
      let #(method, uri, headers, body) =
        svc.build_unit_input_and_output_request(svc.UnitInputAndOutputInput)
      Ok(BuiltRequest(method: method, uri: uri, headers: headers, body: body))
    },
    parse_response: empty_response_parser(
      svc.parse_unit_input_and_output_response,
    ),
  )
}

fn empty_response_parser(
  parser: fn(Int, _, BitArray) -> Result(_, String),
) -> fn(ParsedResponseInput) -> Result(dispatch.ParsedResponse, String) {
  fn(input: ParsedResponseInput) {
    case parser(input.code, input.headers, input.body) {
      Ok(_) -> Ok(ParsedOutput(json: "{}"))
      Error(e) -> Error(e)
    }
  }
}
