//// Auto-generated by scripts/emit-dispatchers.py for restxml.
//// DO NOT EDIT manually — re-run the script after regenerating the
//// service module.

import aws/services/protocoltests/restxml as svc
import protocol_tests/dispatch.{
  type Dispatcher, type ParsedResponseInput, type Registry, BuiltRequest,
  Dispatcher, ParsedOutput,
}

pub fn register_all(registry: Registry) -> Registry {
  registry
  |> dispatch.register(datetime_offsets_dispatcher())
  |> dispatch.register(empty_input_and_empty_output_dispatcher())
  |> dispatch.register(endpoint_operation_dispatcher())
  |> dispatch.register(flattened_xml_map_with_xml_namespace_dispatcher())
  |> dispatch.register(fractional_seconds_dispatcher())
  |> dispatch.register(greeting_with_errors_dispatcher())
  |> dispatch.register(http_response_code_dispatcher())
  |> dispatch.register(ignore_query_params_in_response_dispatcher())
  |> dispatch.register(no_input_and_no_output_dispatcher())
  |> dispatch.register(no_input_and_output_dispatcher())
}

fn datetime_offsets_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#DatetimeOffsets",
    build_request: fn(_params) {
      let #(method, uri, headers, body) =
        svc.build_datetime_offsets_request(svc.DatetimeOffsetsInput)
      Ok(BuiltRequest(method: method, uri: uri, headers: headers, body: body))
    },
    parse_response: empty_response_parser(svc.parse_datetime_offsets_response),
  )
}

fn empty_input_and_empty_output_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#EmptyInputAndEmptyOutput",
    build_request: fn(_params) {
      let #(method, uri, headers, body) =
        svc.build_empty_input_and_empty_output_request(
          svc.EmptyInputAndEmptyOutputInput,
        )
      Ok(BuiltRequest(method: method, uri: uri, headers: headers, body: body))
    },
    parse_response: empty_response_parser(
      svc.parse_empty_input_and_empty_output_response,
    ),
  )
}

fn endpoint_operation_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#EndpointOperation",
    build_request: fn(_params) {
      let #(method, uri, headers, body) =
        svc.build_endpoint_operation_request(svc.EndpointOperationInput)
      Ok(BuiltRequest(method: method, uri: uri, headers: headers, body: body))
    },
    parse_response: empty_response_parser(svc.parse_endpoint_operation_response),
  )
}

fn flattened_xml_map_with_xml_namespace_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#FlattenedXmlMapWithXmlNamespace",
    build_request: fn(_params) {
      let #(method, uri, headers, body) =
        svc.build_flattened_xml_map_with_xml_namespace_request(
          svc.FlattenedXmlMapWithXmlNamespaceInput,
        )
      Ok(BuiltRequest(method: method, uri: uri, headers: headers, body: body))
    },
    parse_response: empty_response_parser(
      svc.parse_flattened_xml_map_with_xml_namespace_response,
    ),
  )
}

fn fractional_seconds_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#FractionalSeconds",
    build_request: fn(_params) {
      let #(method, uri, headers, body) =
        svc.build_fractional_seconds_request(svc.FractionalSecondsInput)
      Ok(BuiltRequest(method: method, uri: uri, headers: headers, body: body))
    },
    parse_response: empty_response_parser(svc.parse_fractional_seconds_response),
  )
}

fn greeting_with_errors_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#GreetingWithErrors",
    build_request: fn(_params) {
      let #(method, uri, headers, body) =
        svc.build_greeting_with_errors_request(svc.GreetingWithErrorsInput)
      Ok(BuiltRequest(method: method, uri: uri, headers: headers, body: body))
    },
    parse_response: empty_response_parser(
      svc.parse_greeting_with_errors_response,
    ),
  )
}

fn http_response_code_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#HttpResponseCode",
    build_request: fn(_params) {
      let #(method, uri, headers, body) =
        svc.build_http_response_code_request(svc.HttpResponseCodeInput)
      Ok(BuiltRequest(method: method, uri: uri, headers: headers, body: body))
    },
    parse_response: empty_response_parser(svc.parse_http_response_code_response),
  )
}

fn ignore_query_params_in_response_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#IgnoreQueryParamsInResponse",
    build_request: fn(_params) {
      let #(method, uri, headers, body) =
        svc.build_ignore_query_params_in_response_request(
          svc.IgnoreQueryParamsInResponseInput,
        )
      Ok(BuiltRequest(method: method, uri: uri, headers: headers, body: body))
    },
    parse_response: empty_response_parser(
      svc.parse_ignore_query_params_in_response_response,
    ),
  )
}

fn no_input_and_no_output_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#NoInputAndNoOutput",
    build_request: fn(_params) {
      let #(method, uri, headers, body) =
        svc.build_no_input_and_no_output_request(svc.NoInputAndNoOutputInput)
      Ok(BuiltRequest(method: method, uri: uri, headers: headers, body: body))
    },
    parse_response: empty_response_parser(
      svc.parse_no_input_and_no_output_response,
    ),
  )
}

fn no_input_and_output_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#NoInputAndOutput",
    build_request: fn(_params) {
      let #(method, uri, headers, body) =
        svc.build_no_input_and_output_request(svc.NoInputAndOutputInput)
      Ok(BuiltRequest(method: method, uri: uri, headers: headers, body: body))
    },
    parse_response: empty_response_parser(
      svc.parse_no_input_and_output_response,
    ),
  )
}

fn empty_response_parser(
  parser: fn(Int, _, BitArray) -> Result(_, String),
) -> fn(ParsedResponseInput) -> Result(dispatch.ParsedResponse, String) {
  fn(input: ParsedResponseInput) {
    case parser(input.code, input.headers, input.body) {
      Ok(_) -> Ok(ParsedOutput(json: "{}"))
      Error(e) -> Error(e)
    }
  }
}
