//// Auto-generated by scripts/emit-dispatchers.py for restjson1.
//// DO NOT EDIT manually — re-run the script after regenerating the
//// service module.

import aws/services/protocoltests/restjson1 as svc
import protocol_tests/dispatch.{
  type Dispatcher, type ParsedResponseInput, type Registry, BuiltRequest,
  Dispatcher, ParsedOutput,
}

pub fn register_all(registry: Registry) -> Registry {
  registry
  |> dispatch.register(all_query_string_types_dispatcher())
  |> dispatch.register(constant_and_variable_query_string_dispatcher())
  |> dispatch.register(constant_query_string_dispatcher())
  |> dispatch.register(content_type_parameters_dispatcher())
  |> dispatch.register(datetime_offsets_dispatcher())
  |> dispatch.register(document_type_dispatcher())
  |> dispatch.register(document_type_as_map_value_dispatcher())
  |> dispatch.register(document_type_as_payload_dispatcher())
  |> dispatch.register(duplex_stream_dispatcher())
  |> dispatch.register(duplex_stream_with_distinct_streams_dispatcher())
  |> dispatch.register(duplex_stream_with_initial_messages_dispatcher())
  |> dispatch.register(empty_input_and_empty_output_dispatcher())
  |> dispatch.register(endpoint_operation_dispatcher())
  |> dispatch.register(endpoint_with_host_label_operation_dispatcher())
  |> dispatch.register(fractional_seconds_dispatcher())
  |> dispatch.register(greeting_with_errors_dispatcher())
  |> dispatch.register(host_with_path_operation_dispatcher())
  |> dispatch.register(http_empty_prefix_headers_dispatcher())
  |> dispatch.register(http_enum_payload_dispatcher())
  |> dispatch.register(http_payload_traits_dispatcher())
  |> dispatch.register(http_payload_traits_with_media_type_dispatcher())
  |> dispatch.register(http_payload_with_structure_dispatcher())
  |> dispatch.register(http_payload_with_union_dispatcher())
  |> dispatch.register(http_prefix_headers_dispatcher())
  |> dispatch.register(http_prefix_headers_in_response_dispatcher())
  |> dispatch.register(http_query_params_only_operation_dispatcher())
  |> dispatch.register(http_request_with_float_labels_dispatcher())
  |> dispatch.register(http_request_with_greedy_label_in_path_dispatcher())
  |> dispatch.register(http_request_with_labels_dispatcher())
  |> dispatch.register(
    http_request_with_labels_and_timestamp_format_dispatcher(),
  )
  |> dispatch.register(http_request_with_regex_literal_dispatcher())
  |> dispatch.register(http_response_code_dispatcher())
  |> dispatch.register(http_string_payload_dispatcher())
  |> dispatch.register(ignore_query_params_in_response_dispatcher())
  |> dispatch.register(input_and_output_with_headers_dispatcher())
  |> dispatch.register(input_stream_dispatcher())
  |> dispatch.register(input_stream_with_initial_request_dispatcher())
  |> dispatch.register(json_blobs_dispatcher())
  |> dispatch.register(json_enums_dispatcher())
  |> dispatch.register(json_int_enums_dispatcher())
  |> dispatch.register(json_lists_dispatcher())
  |> dispatch.register(json_maps_dispatcher())
  |> dispatch.register(json_timestamps_dispatcher())
  |> dispatch.register(json_unions_dispatcher())
  |> dispatch.register(malformed_accept_with_body_dispatcher())
  |> dispatch.register(malformed_accept_with_generic_string_dispatcher())
  |> dispatch.register(malformed_accept_with_payload_dispatcher())
  |> dispatch.register(malformed_blob_dispatcher())
  |> dispatch.register(malformed_boolean_dispatcher())
  |> dispatch.register(malformed_byte_dispatcher())
  |> dispatch.register(malformed_content_type_with_body_dispatcher())
  |> dispatch.register(malformed_content_type_with_generic_string_dispatcher())
  |> dispatch.register(malformed_content_type_without_body_dispatcher())
  |> dispatch.register(
    malformed_content_type_without_body_empty_input_dispatcher(),
  )
  |> dispatch.register(malformed_content_type_with_payload_dispatcher())
  |> dispatch.register(malformed_double_dispatcher())
  |> dispatch.register(malformed_float_dispatcher())
  |> dispatch.register(malformed_integer_dispatcher())
  |> dispatch.register(malformed_list_dispatcher())
  |> dispatch.register(malformed_long_dispatcher())
  |> dispatch.register(malformed_map_dispatcher())
  |> dispatch.register(malformed_request_body_dispatcher())
  |> dispatch.register(malformed_short_dispatcher())
  |> dispatch.register(malformed_string_dispatcher())
  |> dispatch.register(malformed_timestamp_body_date_time_dispatcher())
  |> dispatch.register(malformed_timestamp_body_default_dispatcher())
  |> dispatch.register(malformed_timestamp_body_http_date_dispatcher())
  |> dispatch.register(malformed_timestamp_header_date_time_dispatcher())
  |> dispatch.register(malformed_timestamp_header_default_dispatcher())
  |> dispatch.register(malformed_timestamp_header_epoch_dispatcher())
  |> dispatch.register(malformed_timestamp_path_default_dispatcher())
  |> dispatch.register(malformed_timestamp_path_epoch_dispatcher())
  |> dispatch.register(malformed_timestamp_path_http_date_dispatcher())
  |> dispatch.register(malformed_timestamp_query_default_dispatcher())
  |> dispatch.register(malformed_timestamp_query_epoch_dispatcher())
  |> dispatch.register(malformed_timestamp_query_http_date_dispatcher())
  |> dispatch.register(malformed_union_dispatcher())
  |> dispatch.register(media_type_header_dispatcher())
  |> dispatch.register(no_input_and_no_output_dispatcher())
  |> dispatch.register(no_input_and_output_dispatcher())
  |> dispatch.register(null_and_empty_headers_client_dispatcher())
  |> dispatch.register(null_and_empty_headers_server_dispatcher())
  |> dispatch.register(omits_null_serializes_empty_string_dispatcher())
  |> dispatch.register(omits_serializing_empty_lists_dispatcher())
  |> dispatch.register(operation_with_defaults_dispatcher())
  |> dispatch.register(operation_with_nested_structure_dispatcher())
  |> dispatch.register(output_stream_dispatcher())
  |> dispatch.register(output_stream_with_initial_response_dispatcher())
  |> dispatch.register(post_player_action_dispatcher())
  |> dispatch.register(post_union_with_json_name_dispatcher())
  |> dispatch.register(put_with_content_encoding_dispatcher())
  |> dispatch.register(query_idempotency_token_auto_fill_dispatcher())
  |> dispatch.register(query_params_as_string_list_map_dispatcher())
  |> dispatch.register(query_precedence_dispatcher())
  |> dispatch.register(recursive_shapes_dispatcher())
  |> dispatch.register(response_code_http_fallback_dispatcher())
  |> dispatch.register(response_code_required_dispatcher())
  |> dispatch.register(simple_scalar_properties_dispatcher())
  |> dispatch.register(sparse_json_lists_dispatcher())
  |> dispatch.register(sparse_json_maps_dispatcher())
  |> dispatch.register(streaming_traits_dispatcher())
  |> dispatch.register(streaming_traits_require_length_dispatcher())
  |> dispatch.register(streaming_traits_with_media_type_dispatcher())
  |> dispatch.register(test_body_structure_dispatcher())
  |> dispatch.register(test_get_no_input_no_payload_dispatcher())
  |> dispatch.register(test_get_no_payload_dispatcher())
  |> dispatch.register(test_payload_blob_dispatcher())
  |> dispatch.register(test_payload_structure_dispatcher())
  |> dispatch.register(test_post_no_input_no_payload_dispatcher())
  |> dispatch.register(test_post_no_payload_dispatcher())
  |> dispatch.register(timestamp_format_headers_dispatcher())
  |> dispatch.register(unit_input_and_output_dispatcher())
}

fn all_query_string_types_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#AllQueryStringTypes",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_all_query_string_types_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_all_query_string_types_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_all_query_string_types_response),
  )
}

fn constant_and_variable_query_string_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#ConstantAndVariableQueryString",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_constant_and_variable_query_string_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_constant_and_variable_query_string_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_constant_and_variable_query_string_response,
    ),
  )
}

fn constant_query_string_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#ConstantQueryString",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_constant_query_string_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_constant_query_string_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_constant_query_string_response),
  )
}

fn content_type_parameters_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#ContentTypeParameters",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_content_type_parameters_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_content_type_parameters_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_content_type_parameters_response),
  )
}

fn datetime_offsets_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#DatetimeOffsets",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_datetime_offsets_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_datetime_offsets_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_datetime_offsets_response),
  )
}

fn document_type_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#DocumentType",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_document_type_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_document_type_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_document_type_response),
  )
}

fn document_type_as_map_value_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#DocumentTypeAsMapValue",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_document_type_as_map_value_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_document_type_as_map_value_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_document_type_as_map_value_response,
    ),
  )
}

fn document_type_as_payload_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#DocumentTypeAsPayload",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_document_type_as_payload_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_document_type_as_payload_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_document_type_as_payload_response),
  )
}

fn duplex_stream_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#DuplexStream",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_duplex_stream_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_duplex_stream_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_duplex_stream_response),
  )
}

fn duplex_stream_with_distinct_streams_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#DuplexStreamWithDistinctStreams",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_duplex_stream_with_distinct_streams_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_duplex_stream_with_distinct_streams_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_duplex_stream_with_distinct_streams_response,
    ),
  )
}

fn duplex_stream_with_initial_messages_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#DuplexStreamWithInitialMessages",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_duplex_stream_with_initial_messages_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_duplex_stream_with_initial_messages_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_duplex_stream_with_initial_messages_response,
    ),
  )
}

fn empty_input_and_empty_output_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#EmptyInputAndEmptyOutput",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_empty_input_and_empty_output_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_empty_input_and_empty_output_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_empty_input_and_empty_output_response,
    ),
  )
}

fn endpoint_operation_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#EndpointOperation",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_endpoint_operation_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_endpoint_operation_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_endpoint_operation_response),
  )
}

fn endpoint_with_host_label_operation_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#EndpointWithHostLabelOperation",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_endpoint_with_host_label_operation_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_endpoint_with_host_label_operation_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_endpoint_with_host_label_operation_response,
    ),
  )
}

fn fractional_seconds_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#FractionalSeconds",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_fractional_seconds_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_fractional_seconds_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_fractional_seconds_response),
  )
}

fn greeting_with_errors_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#GreetingWithErrors",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_greeting_with_errors_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_greeting_with_errors_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_greeting_with_errors_response),
  )
}

fn host_with_path_operation_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#HostWithPathOperation",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_host_with_path_operation_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_host_with_path_operation_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_host_with_path_operation_response),
  )
}

fn http_empty_prefix_headers_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#HttpEmptyPrefixHeaders",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_http_empty_prefix_headers_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_http_empty_prefix_headers_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_http_empty_prefix_headers_response,
    ),
  )
}

fn http_enum_payload_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#HttpEnumPayload",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_http_enum_payload_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_http_enum_payload_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_http_enum_payload_response),
  )
}

fn http_payload_traits_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#HttpPayloadTraits",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_http_payload_traits_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_http_payload_traits_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_http_payload_traits_response),
  )
}

fn http_payload_traits_with_media_type_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#HttpPayloadTraitsWithMediaType",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_http_payload_traits_with_media_type_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_http_payload_traits_with_media_type_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_http_payload_traits_with_media_type_response,
    ),
  )
}

fn http_payload_with_structure_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#HttpPayloadWithStructure",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_http_payload_with_structure_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_http_payload_with_structure_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_http_payload_with_structure_response,
    ),
  )
}

fn http_payload_with_union_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#HttpPayloadWithUnion",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_http_payload_with_union_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_http_payload_with_union_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_http_payload_with_union_response),
  )
}

fn http_prefix_headers_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#HttpPrefixHeaders",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_http_prefix_headers_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_http_prefix_headers_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_http_prefix_headers_response),
  )
}

fn http_prefix_headers_in_response_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#HttpPrefixHeadersInResponse",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_http_prefix_headers_in_response_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_http_prefix_headers_in_response_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_http_prefix_headers_in_response_response,
    ),
  )
}

fn http_query_params_only_operation_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#HttpQueryParamsOnlyOperation",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_http_query_params_only_operation_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_http_query_params_only_operation_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_http_query_params_only_operation_response,
    ),
  )
}

fn http_request_with_float_labels_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#HttpRequestWithFloatLabels",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_http_request_with_float_labels_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_http_request_with_float_labels_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_http_request_with_float_labels_response,
    ),
  )
}

fn http_request_with_greedy_label_in_path_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#HttpRequestWithGreedyLabelInPath",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_http_request_with_greedy_label_in_path_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_http_request_with_greedy_label_in_path_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_http_request_with_greedy_label_in_path_response,
    ),
  )
}

fn http_request_with_labels_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#HttpRequestWithLabels",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_http_request_with_labels_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_http_request_with_labels_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_http_request_with_labels_response),
  )
}

fn http_request_with_labels_and_timestamp_format_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#HttpRequestWithLabelsAndTimestampFormat",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_http_request_with_labels_and_timestamp_format_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_http_request_with_labels_and_timestamp_format_request(
              input,
            )
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_http_request_with_labels_and_timestamp_format_response,
    ),
  )
}

fn http_request_with_regex_literal_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#HttpRequestWithRegexLiteral",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_http_request_with_regex_literal_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_http_request_with_regex_literal_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_http_request_with_regex_literal_response,
    ),
  )
}

fn http_response_code_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#HttpResponseCode",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_http_response_code_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_http_response_code_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_http_response_code_response),
  )
}

fn http_string_payload_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#HttpStringPayload",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_http_string_payload_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_http_string_payload_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_http_string_payload_response),
  )
}

fn ignore_query_params_in_response_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#IgnoreQueryParamsInResponse",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_ignore_query_params_in_response_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_ignore_query_params_in_response_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_ignore_query_params_in_response_response,
    ),
  )
}

fn input_and_output_with_headers_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#InputAndOutputWithHeaders",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_input_and_output_with_headers_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_input_and_output_with_headers_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_input_and_output_with_headers_response,
    ),
  )
}

fn input_stream_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#InputStream",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_input_stream_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_input_stream_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_input_stream_response),
  )
}

fn input_stream_with_initial_request_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#InputStreamWithInitialRequest",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_input_stream_with_initial_request_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_input_stream_with_initial_request_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_input_stream_with_initial_request_response,
    ),
  )
}

fn json_blobs_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#JsonBlobs",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_json_blobs_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_json_blobs_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_json_blobs_response),
  )
}

fn json_enums_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#JsonEnums",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_json_enums_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_json_enums_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_json_enums_response),
  )
}

fn json_int_enums_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#JsonIntEnums",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_json_int_enums_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_json_int_enums_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_json_int_enums_response),
  )
}

fn json_lists_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#JsonLists",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_json_lists_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_json_lists_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_json_lists_response),
  )
}

fn json_maps_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#JsonMaps",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_json_maps_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) = svc.build_json_maps_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_json_maps_response),
  )
}

fn json_timestamps_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#JsonTimestamps",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_json_timestamps_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_json_timestamps_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_json_timestamps_response),
  )
}

fn json_unions_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#JsonUnions",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_json_unions_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_json_unions_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_json_unions_response),
  )
}

fn malformed_accept_with_body_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#MalformedAcceptWithBody",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_malformed_accept_with_body_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_malformed_accept_with_body_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_malformed_accept_with_body_response,
    ),
  )
}

fn malformed_accept_with_generic_string_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#MalformedAcceptWithGenericString",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_malformed_accept_with_generic_string_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_malformed_accept_with_generic_string_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_malformed_accept_with_generic_string_response,
    ),
  )
}

fn malformed_accept_with_payload_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#MalformedAcceptWithPayload",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_malformed_accept_with_payload_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_malformed_accept_with_payload_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_malformed_accept_with_payload_response,
    ),
  )
}

fn malformed_blob_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#MalformedBlob",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_malformed_blob_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_malformed_blob_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_malformed_blob_response),
  )
}

fn malformed_boolean_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#MalformedBoolean",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_malformed_boolean_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_malformed_boolean_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_malformed_boolean_response),
  )
}

fn malformed_byte_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#MalformedByte",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_malformed_byte_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_malformed_byte_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_malformed_byte_response),
  )
}

fn malformed_content_type_with_body_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#MalformedContentTypeWithBody",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_malformed_content_type_with_body_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_malformed_content_type_with_body_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_malformed_content_type_with_body_response,
    ),
  )
}

fn malformed_content_type_with_generic_string_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#MalformedContentTypeWithGenericString",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_malformed_content_type_with_generic_string_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_malformed_content_type_with_generic_string_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_malformed_content_type_with_generic_string_response,
    ),
  )
}

fn malformed_content_type_without_body_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#MalformedContentTypeWithoutBody",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_malformed_content_type_without_body_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_malformed_content_type_without_body_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_malformed_content_type_without_body_response,
    ),
  )
}

fn malformed_content_type_without_body_empty_input_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#MalformedContentTypeWithoutBodyEmptyInput",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case
        svc.decode_malformed_content_type_without_body_empty_input_input(raw)
      {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_malformed_content_type_without_body_empty_input_request(
              input,
            )
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_malformed_content_type_without_body_empty_input_response,
    ),
  )
}

fn malformed_content_type_with_payload_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#MalformedContentTypeWithPayload",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_malformed_content_type_with_payload_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_malformed_content_type_with_payload_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_malformed_content_type_with_payload_response,
    ),
  )
}

fn malformed_double_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#MalformedDouble",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_malformed_double_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_malformed_double_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_malformed_double_response),
  )
}

fn malformed_float_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#MalformedFloat",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_malformed_float_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_malformed_float_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_malformed_float_response),
  )
}

fn malformed_integer_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#MalformedInteger",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_malformed_integer_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_malformed_integer_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_malformed_integer_response),
  )
}

fn malformed_list_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#MalformedList",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_malformed_list_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_malformed_list_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_malformed_list_response),
  )
}

fn malformed_long_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#MalformedLong",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_malformed_long_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_malformed_long_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_malformed_long_response),
  )
}

fn malformed_map_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#MalformedMap",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_malformed_map_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_malformed_map_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_malformed_map_response),
  )
}

fn malformed_request_body_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#MalformedRequestBody",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_malformed_request_body_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_malformed_request_body_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_malformed_request_body_response),
  )
}

fn malformed_short_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#MalformedShort",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_malformed_short_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_malformed_short_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_malformed_short_response),
  )
}

fn malformed_string_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#MalformedString",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_malformed_string_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_malformed_string_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_malformed_string_response),
  )
}

fn malformed_timestamp_body_date_time_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#MalformedTimestampBodyDateTime",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_malformed_timestamp_body_date_time_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_malformed_timestamp_body_date_time_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_malformed_timestamp_body_date_time_response,
    ),
  )
}

fn malformed_timestamp_body_default_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#MalformedTimestampBodyDefault",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_malformed_timestamp_body_default_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_malformed_timestamp_body_default_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_malformed_timestamp_body_default_response,
    ),
  )
}

fn malformed_timestamp_body_http_date_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#MalformedTimestampBodyHttpDate",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_malformed_timestamp_body_http_date_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_malformed_timestamp_body_http_date_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_malformed_timestamp_body_http_date_response,
    ),
  )
}

fn malformed_timestamp_header_date_time_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#MalformedTimestampHeaderDateTime",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_malformed_timestamp_header_date_time_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_malformed_timestamp_header_date_time_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_malformed_timestamp_header_date_time_response,
    ),
  )
}

fn malformed_timestamp_header_default_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#MalformedTimestampHeaderDefault",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_malformed_timestamp_header_default_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_malformed_timestamp_header_default_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_malformed_timestamp_header_default_response,
    ),
  )
}

fn malformed_timestamp_header_epoch_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#MalformedTimestampHeaderEpoch",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_malformed_timestamp_header_epoch_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_malformed_timestamp_header_epoch_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_malformed_timestamp_header_epoch_response,
    ),
  )
}

fn malformed_timestamp_path_default_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#MalformedTimestampPathDefault",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_malformed_timestamp_path_default_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_malformed_timestamp_path_default_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_malformed_timestamp_path_default_response,
    ),
  )
}

fn malformed_timestamp_path_epoch_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#MalformedTimestampPathEpoch",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_malformed_timestamp_path_epoch_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_malformed_timestamp_path_epoch_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_malformed_timestamp_path_epoch_response,
    ),
  )
}

fn malformed_timestamp_path_http_date_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#MalformedTimestampPathHttpDate",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_malformed_timestamp_path_http_date_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_malformed_timestamp_path_http_date_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_malformed_timestamp_path_http_date_response,
    ),
  )
}

fn malformed_timestamp_query_default_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#MalformedTimestampQueryDefault",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_malformed_timestamp_query_default_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_malformed_timestamp_query_default_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_malformed_timestamp_query_default_response,
    ),
  )
}

fn malformed_timestamp_query_epoch_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#MalformedTimestampQueryEpoch",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_malformed_timestamp_query_epoch_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_malformed_timestamp_query_epoch_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_malformed_timestamp_query_epoch_response,
    ),
  )
}

fn malformed_timestamp_query_http_date_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#MalformedTimestampQueryHttpDate",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_malformed_timestamp_query_http_date_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_malformed_timestamp_query_http_date_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_malformed_timestamp_query_http_date_response,
    ),
  )
}

fn malformed_union_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#MalformedUnion",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_malformed_union_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_malformed_union_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_malformed_union_response),
  )
}

fn media_type_header_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#MediaTypeHeader",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_media_type_header_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_media_type_header_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_media_type_header_response),
  )
}

fn no_input_and_no_output_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#NoInputAndNoOutput",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_no_input_and_no_output_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_no_input_and_no_output_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_no_input_and_no_output_response),
  )
}

fn no_input_and_output_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#NoInputAndOutput",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_no_input_and_output_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_no_input_and_output_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_no_input_and_output_response),
  )
}

fn null_and_empty_headers_client_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#NullAndEmptyHeadersClient",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_null_and_empty_headers_client_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_null_and_empty_headers_client_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_null_and_empty_headers_client_response,
    ),
  )
}

fn null_and_empty_headers_server_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#NullAndEmptyHeadersServer",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_null_and_empty_headers_server_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_null_and_empty_headers_server_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_null_and_empty_headers_server_response,
    ),
  )
}

fn omits_null_serializes_empty_string_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#OmitsNullSerializesEmptyString",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_omits_null_serializes_empty_string_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_omits_null_serializes_empty_string_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_omits_null_serializes_empty_string_response,
    ),
  )
}

fn omits_serializing_empty_lists_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#OmitsSerializingEmptyLists",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_omits_serializing_empty_lists_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_omits_serializing_empty_lists_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_omits_serializing_empty_lists_response,
    ),
  )
}

fn operation_with_defaults_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#OperationWithDefaults",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_operation_with_defaults_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_operation_with_defaults_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_operation_with_defaults_response),
  )
}

fn operation_with_nested_structure_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#OperationWithNestedStructure",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_operation_with_nested_structure_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_operation_with_nested_structure_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_operation_with_nested_structure_response,
    ),
  )
}

fn output_stream_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#OutputStream",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_output_stream_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_output_stream_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_output_stream_response),
  )
}

fn output_stream_with_initial_response_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#OutputStreamWithInitialResponse",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_output_stream_with_initial_response_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_output_stream_with_initial_response_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_output_stream_with_initial_response_response,
    ),
  )
}

fn post_player_action_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#PostPlayerAction",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_post_player_action_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_post_player_action_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_post_player_action_response),
  )
}

fn post_union_with_json_name_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#PostUnionWithJsonName",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_post_union_with_json_name_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_post_union_with_json_name_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_post_union_with_json_name_response,
    ),
  )
}

fn put_with_content_encoding_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#PutWithContentEncoding",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_put_with_content_encoding_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_put_with_content_encoding_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_put_with_content_encoding_response,
    ),
  )
}

fn query_idempotency_token_auto_fill_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#QueryIdempotencyTokenAutoFill",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_query_idempotency_token_auto_fill_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_query_idempotency_token_auto_fill_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_query_idempotency_token_auto_fill_response,
    ),
  )
}

fn query_params_as_string_list_map_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#QueryParamsAsStringListMap",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_query_params_as_string_list_map_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_query_params_as_string_list_map_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_query_params_as_string_list_map_response,
    ),
  )
}

fn query_precedence_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#QueryPrecedence",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_query_precedence_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_query_precedence_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_query_precedence_response),
  )
}

fn recursive_shapes_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#RecursiveShapes",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_recursive_shapes_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_recursive_shapes_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_recursive_shapes_response),
  )
}

fn response_code_http_fallback_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#ResponseCodeHttpFallback",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_response_code_http_fallback_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_response_code_http_fallback_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_response_code_http_fallback_response,
    ),
  )
}

fn response_code_required_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#ResponseCodeRequired",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_response_code_required_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_response_code_required_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_response_code_required_response),
  )
}

fn simple_scalar_properties_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#SimpleScalarProperties",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_simple_scalar_properties_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_simple_scalar_properties_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_simple_scalar_properties_response),
  )
}

fn sparse_json_lists_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#SparseJsonLists",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_sparse_json_lists_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_sparse_json_lists_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_sparse_json_lists_response),
  )
}

fn sparse_json_maps_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#SparseJsonMaps",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_sparse_json_maps_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_sparse_json_maps_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_sparse_json_maps_response),
  )
}

fn streaming_traits_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#StreamingTraits",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_streaming_traits_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_streaming_traits_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_streaming_traits_response),
  )
}

fn streaming_traits_require_length_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#StreamingTraitsRequireLength",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_streaming_traits_require_length_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_streaming_traits_require_length_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_streaming_traits_require_length_response,
    ),
  )
}

fn streaming_traits_with_media_type_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#StreamingTraitsWithMediaType",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_streaming_traits_with_media_type_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_streaming_traits_with_media_type_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_streaming_traits_with_media_type_response,
    ),
  )
}

fn test_body_structure_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#TestBodyStructure",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_test_body_structure_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_test_body_structure_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_test_body_structure_response),
  )
}

fn test_get_no_input_no_payload_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#TestGetNoInputNoPayload",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_test_get_no_input_no_payload_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_test_get_no_input_no_payload_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_test_get_no_input_no_payload_response,
    ),
  )
}

fn test_get_no_payload_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#TestGetNoPayload",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_test_get_no_payload_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_test_get_no_payload_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_test_get_no_payload_response),
  )
}

fn test_payload_blob_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#TestPayloadBlob",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_test_payload_blob_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_test_payload_blob_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_test_payload_blob_response),
  )
}

fn test_payload_structure_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#TestPayloadStructure",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_test_payload_structure_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_test_payload_structure_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_test_payload_structure_response),
  )
}

fn test_post_no_input_no_payload_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#TestPostNoInputNoPayload",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_test_post_no_input_no_payload_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_test_post_no_input_no_payload_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_test_post_no_input_no_payload_response,
    ),
  )
}

fn test_post_no_payload_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#TestPostNoPayload",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_test_post_no_payload_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_test_post_no_payload_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_test_post_no_payload_response),
  )
}

fn timestamp_format_headers_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#TimestampFormatHeaders",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_timestamp_format_headers_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_timestamp_format_headers_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_timestamp_format_headers_response),
  )
}

fn unit_input_and_output_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restjson#UnitInputAndOutput",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_unit_input_and_output_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_unit_input_and_output_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_unit_input_and_output_response),
  )
}

fn response_parser(
  parser: fn(Int, _, BitArray) -> Result(_, String),
) -> fn(ParsedResponseInput) -> Result(dispatch.ParsedResponse, String) {
  fn(input: ParsedResponseInput) {
    case parser(input.code, input.headers, input.body) {
      Ok(_) -> Ok(ParsedOutput(json: "{}"))
      Error(e) -> Error(e)
    }
  }
}
