//// Auto-generated by codegen/dispatcher.gleam for restxml.
//// DO NOT EDIT manually — re-run `./scripts/regen.sh` after
//// regenerating the service module.

import aws/services/protocoltests/restxml as svc
import protocol_tests/dispatch.{
  type Dispatcher, type ParsedResponseInput, type Registry, BuiltRequest,
  Dispatcher, ParsedOutput,
}

pub fn register_all(registry: Registry) -> Registry {
  registry
  |> dispatch.register(all_query_string_types_dispatcher())
  |> dispatch.register(body_with_xml_name_dispatcher())
  |> dispatch.register(constant_and_variable_query_string_dispatcher())
  |> dispatch.register(constant_query_string_dispatcher())
  |> dispatch.register(content_type_parameters_dispatcher())
  |> dispatch.register(datetime_offsets_dispatcher())
  |> dispatch.register(empty_input_and_empty_output_dispatcher())
  |> dispatch.register(endpoint_operation_dispatcher())
  |> dispatch.register(endpoint_with_host_label_header_operation_dispatcher())
  |> dispatch.register(endpoint_with_host_label_operation_dispatcher())
  |> dispatch.register(flattened_xml_map_dispatcher())
  |> dispatch.register(flattened_xml_map_with_xml_name_dispatcher())
  |> dispatch.register(flattened_xml_map_with_xml_namespace_dispatcher())
  |> dispatch.register(fractional_seconds_dispatcher())
  |> dispatch.register(greeting_with_errors_dispatcher())
  |> dispatch.register(http_empty_prefix_headers_dispatcher())
  |> dispatch.register(http_enum_payload_dispatcher())
  |> dispatch.register(http_payload_traits_dispatcher())
  |> dispatch.register(http_payload_traits_with_media_type_dispatcher())
  |> dispatch.register(http_payload_with_member_xml_name_dispatcher())
  |> dispatch.register(http_payload_with_structure_dispatcher())
  |> dispatch.register(http_payload_with_union_dispatcher())
  |> dispatch.register(http_payload_with_xml_name_dispatcher())
  |> dispatch.register(http_payload_with_xml_namespace_dispatcher())
  |> dispatch.register(http_payload_with_xml_namespace_and_prefix_dispatcher())
  |> dispatch.register(http_prefix_headers_dispatcher())
  |> dispatch.register(http_request_with_float_labels_dispatcher())
  |> dispatch.register(http_request_with_greedy_label_in_path_dispatcher())
  |> dispatch.register(http_request_with_labels_dispatcher())
  |> dispatch.register(
    http_request_with_labels_and_timestamp_format_dispatcher(),
  )
  |> dispatch.register(http_response_code_dispatcher())
  |> dispatch.register(http_string_payload_dispatcher())
  |> dispatch.register(ignore_query_params_in_response_dispatcher())
  |> dispatch.register(input_and_output_with_headers_dispatcher())
  |> dispatch.register(nested_xml_maps_dispatcher())
  |> dispatch.register(nested_xml_map_with_xml_name_dispatcher())
  |> dispatch.register(no_input_and_no_output_dispatcher())
  |> dispatch.register(no_input_and_output_dispatcher())
  |> dispatch.register(null_and_empty_headers_client_dispatcher())
  |> dispatch.register(null_and_empty_headers_server_dispatcher())
  |> dispatch.register(omits_null_serializes_empty_string_dispatcher())
  |> dispatch.register(put_with_content_encoding_dispatcher())
  |> dispatch.register(query_idempotency_token_auto_fill_dispatcher())
  |> dispatch.register(query_params_as_string_list_map_dispatcher())
  |> dispatch.register(query_precedence_dispatcher())
  |> dispatch.register(recursive_shapes_dispatcher())
  |> dispatch.register(simple_scalar_properties_dispatcher())
  |> dispatch.register(timestamp_format_headers_dispatcher())
  |> dispatch.register(xml_attributes_dispatcher())
  |> dispatch.register(xml_attributes_in_middle_dispatcher())
  |> dispatch.register(xml_attributes_on_payload_dispatcher())
  |> dispatch.register(xml_blobs_dispatcher())
  |> dispatch.register(xml_empty_blobs_dispatcher())
  |> dispatch.register(xml_empty_lists_dispatcher())
  |> dispatch.register(xml_empty_maps_dispatcher())
  |> dispatch.register(xml_empty_strings_dispatcher())
  |> dispatch.register(xml_enums_dispatcher())
  |> dispatch.register(xml_int_enums_dispatcher())
  |> dispatch.register(xml_lists_dispatcher())
  |> dispatch.register(xml_maps_dispatcher())
  |> dispatch.register(xml_maps_xml_name_dispatcher())
  |> dispatch.register(xml_map_with_xml_namespace_dispatcher())
  |> dispatch.register(xml_namespaces_dispatcher())
  |> dispatch.register(xml_timestamps_dispatcher())
  |> dispatch.register(xml_unions_dispatcher())
  |> dispatch.register(complex_error_dispatcher())
  |> dispatch.register(invalid_greeting_dispatcher())
}

fn all_query_string_types_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#AllQueryStringTypes",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_all_query_string_types_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_all_query_string_types_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_all_query_string_types_response),
  )
}

fn body_with_xml_name_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#BodyWithXmlName",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_body_with_xml_name_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_body_with_xml_name_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_body_with_xml_name_response),
  )
}

fn constant_and_variable_query_string_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#ConstantAndVariableQueryString",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_constant_and_variable_query_string_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_constant_and_variable_query_string_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_constant_and_variable_query_string_response,
    ),
  )
}

fn constant_query_string_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#ConstantQueryString",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_constant_query_string_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_constant_query_string_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_constant_query_string_response),
  )
}

fn content_type_parameters_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#ContentTypeParameters",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_content_type_parameters_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_content_type_parameters_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_content_type_parameters_response),
  )
}

fn datetime_offsets_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#DatetimeOffsets",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_datetime_offsets_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_datetime_offsets_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_datetime_offsets_response),
  )
}

fn empty_input_and_empty_output_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#EmptyInputAndEmptyOutput",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_empty_input_and_empty_output_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_empty_input_and_empty_output_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_empty_input_and_empty_output_response,
    ),
  )
}

fn endpoint_operation_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#EndpointOperation",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_endpoint_operation_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_endpoint_operation_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_endpoint_operation_response),
  )
}

fn endpoint_with_host_label_header_operation_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#EndpointWithHostLabelHeaderOperation",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_endpoint_with_host_label_header_operation_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_endpoint_with_host_label_header_operation_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_endpoint_with_host_label_header_operation_response,
    ),
  )
}

fn endpoint_with_host_label_operation_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#EndpointWithHostLabelOperation",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_endpoint_with_host_label_operation_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_endpoint_with_host_label_operation_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_endpoint_with_host_label_operation_response,
    ),
  )
}

fn flattened_xml_map_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#FlattenedXmlMap",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_flattened_xml_map_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_flattened_xml_map_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_flattened_xml_map_response),
  )
}

fn flattened_xml_map_with_xml_name_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#FlattenedXmlMapWithXmlName",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_flattened_xml_map_with_xml_name_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_flattened_xml_map_with_xml_name_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_flattened_xml_map_with_xml_name_response,
    ),
  )
}

fn flattened_xml_map_with_xml_namespace_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#FlattenedXmlMapWithXmlNamespace",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_flattened_xml_map_with_xml_namespace_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_flattened_xml_map_with_xml_namespace_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_flattened_xml_map_with_xml_namespace_response,
    ),
  )
}

fn fractional_seconds_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#FractionalSeconds",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_fractional_seconds_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_fractional_seconds_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_fractional_seconds_response),
  )
}

fn greeting_with_errors_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#GreetingWithErrors",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_greeting_with_errors_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_greeting_with_errors_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_greeting_with_errors_response),
  )
}

fn http_empty_prefix_headers_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#HttpEmptyPrefixHeaders",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_http_empty_prefix_headers_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_http_empty_prefix_headers_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_http_empty_prefix_headers_response,
    ),
  )
}

fn http_enum_payload_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#HttpEnumPayload",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_http_enum_payload_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_http_enum_payload_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_http_enum_payload_response),
  )
}

fn http_payload_traits_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#HttpPayloadTraits",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_http_payload_traits_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_http_payload_traits_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_http_payload_traits_response),
  )
}

fn http_payload_traits_with_media_type_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#HttpPayloadTraitsWithMediaType",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_http_payload_traits_with_media_type_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_http_payload_traits_with_media_type_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_http_payload_traits_with_media_type_response,
    ),
  )
}

fn http_payload_with_member_xml_name_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#HttpPayloadWithMemberXmlName",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_http_payload_with_member_xml_name_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_http_payload_with_member_xml_name_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_http_payload_with_member_xml_name_response,
    ),
  )
}

fn http_payload_with_structure_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#HttpPayloadWithStructure",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_http_payload_with_structure_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_http_payload_with_structure_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_http_payload_with_structure_response,
    ),
  )
}

fn http_payload_with_union_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#HttpPayloadWithUnion",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_http_payload_with_union_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_http_payload_with_union_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_http_payload_with_union_response),
  )
}

fn http_payload_with_xml_name_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#HttpPayloadWithXmlName",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_http_payload_with_xml_name_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_http_payload_with_xml_name_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_http_payload_with_xml_name_response,
    ),
  )
}

fn http_payload_with_xml_namespace_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#HttpPayloadWithXmlNamespace",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_http_payload_with_xml_namespace_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_http_payload_with_xml_namespace_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_http_payload_with_xml_namespace_response,
    ),
  )
}

fn http_payload_with_xml_namespace_and_prefix_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#HttpPayloadWithXmlNamespaceAndPrefix",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_http_payload_with_xml_namespace_and_prefix_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_http_payload_with_xml_namespace_and_prefix_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_http_payload_with_xml_namespace_and_prefix_response,
    ),
  )
}

fn http_prefix_headers_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#HttpPrefixHeaders",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_http_prefix_headers_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_http_prefix_headers_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_http_prefix_headers_response),
  )
}

fn http_request_with_float_labels_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#HttpRequestWithFloatLabels",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_http_request_with_float_labels_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_http_request_with_float_labels_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_http_request_with_float_labels_response,
    ),
  )
}

fn http_request_with_greedy_label_in_path_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#HttpRequestWithGreedyLabelInPath",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_http_request_with_greedy_label_in_path_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_http_request_with_greedy_label_in_path_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_http_request_with_greedy_label_in_path_response,
    ),
  )
}

fn http_request_with_labels_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#HttpRequestWithLabels",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_http_request_with_labels_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_http_request_with_labels_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_http_request_with_labels_response),
  )
}

fn http_request_with_labels_and_timestamp_format_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#HttpRequestWithLabelsAndTimestampFormat",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_http_request_with_labels_and_timestamp_format_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_http_request_with_labels_and_timestamp_format_request(
              input,
            )
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_http_request_with_labels_and_timestamp_format_response,
    ),
  )
}

fn http_response_code_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#HttpResponseCode",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_http_response_code_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_http_response_code_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_http_response_code_response),
  )
}

fn http_string_payload_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#HttpStringPayload",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_http_string_payload_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_http_string_payload_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_http_string_payload_response),
  )
}

fn ignore_query_params_in_response_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#IgnoreQueryParamsInResponse",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_ignore_query_params_in_response_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_ignore_query_params_in_response_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_ignore_query_params_in_response_response,
    ),
  )
}

fn input_and_output_with_headers_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#InputAndOutputWithHeaders",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_input_and_output_with_headers_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_input_and_output_with_headers_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_input_and_output_with_headers_response,
    ),
  )
}

fn nested_xml_maps_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#NestedXmlMaps",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_nested_xml_maps_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_nested_xml_maps_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_nested_xml_maps_response),
  )
}

fn nested_xml_map_with_xml_name_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#NestedXmlMapWithXmlName",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_nested_xml_map_with_xml_name_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_nested_xml_map_with_xml_name_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_nested_xml_map_with_xml_name_response,
    ),
  )
}

fn no_input_and_no_output_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#NoInputAndNoOutput",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_no_input_and_no_output_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_no_input_and_no_output_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_no_input_and_no_output_response),
  )
}

fn no_input_and_output_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#NoInputAndOutput",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_no_input_and_output_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_no_input_and_output_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_no_input_and_output_response),
  )
}

fn null_and_empty_headers_client_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#NullAndEmptyHeadersClient",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_null_and_empty_headers_client_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_null_and_empty_headers_client_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_null_and_empty_headers_client_response,
    ),
  )
}

fn null_and_empty_headers_server_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#NullAndEmptyHeadersServer",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_null_and_empty_headers_server_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_null_and_empty_headers_server_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_null_and_empty_headers_server_response,
    ),
  )
}

fn omits_null_serializes_empty_string_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#OmitsNullSerializesEmptyString",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_omits_null_serializes_empty_string_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_omits_null_serializes_empty_string_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_omits_null_serializes_empty_string_response,
    ),
  )
}

fn put_with_content_encoding_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#PutWithContentEncoding",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_put_with_content_encoding_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_put_with_content_encoding_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_put_with_content_encoding_response,
    ),
  )
}

fn query_idempotency_token_auto_fill_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#QueryIdempotencyTokenAutoFill",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_query_idempotency_token_auto_fill_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_query_idempotency_token_auto_fill_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_query_idempotency_token_auto_fill_response,
    ),
  )
}

fn query_params_as_string_list_map_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#QueryParamsAsStringListMap",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_query_params_as_string_list_map_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_query_params_as_string_list_map_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_query_params_as_string_list_map_response,
    ),
  )
}

fn query_precedence_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#QueryPrecedence",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_query_precedence_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_query_precedence_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_query_precedence_response),
  )
}

fn recursive_shapes_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#RecursiveShapes",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_recursive_shapes_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_recursive_shapes_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_recursive_shapes_response),
  )
}

fn simple_scalar_properties_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#SimpleScalarProperties",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_simple_scalar_properties_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_simple_scalar_properties_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_simple_scalar_properties_response),
  )
}

fn timestamp_format_headers_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#TimestampFormatHeaders",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_timestamp_format_headers_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_timestamp_format_headers_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_timestamp_format_headers_response),
  )
}

fn xml_attributes_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#XmlAttributes",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_xml_attributes_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_xml_attributes_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_xml_attributes_response),
  )
}

fn xml_attributes_in_middle_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#XmlAttributesInMiddle",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_xml_attributes_in_middle_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_xml_attributes_in_middle_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_xml_attributes_in_middle_response),
  )
}

fn xml_attributes_on_payload_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#XmlAttributesOnPayload",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_xml_attributes_on_payload_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_xml_attributes_on_payload_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_xml_attributes_on_payload_response,
    ),
  )
}

fn xml_blobs_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#XmlBlobs",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_xml_blobs_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) = svc.build_xml_blobs_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_xml_blobs_response),
  )
}

fn xml_empty_blobs_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#XmlEmptyBlobs",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_xml_empty_blobs_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_xml_empty_blobs_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_xml_empty_blobs_response),
  )
}

fn xml_empty_lists_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#XmlEmptyLists",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_xml_empty_lists_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_xml_empty_lists_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_xml_empty_lists_response),
  )
}

fn xml_empty_maps_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#XmlEmptyMaps",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_xml_empty_maps_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_xml_empty_maps_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_xml_empty_maps_response),
  )
}

fn xml_empty_strings_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#XmlEmptyStrings",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_xml_empty_strings_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_xml_empty_strings_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_xml_empty_strings_response),
  )
}

fn xml_enums_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#XmlEnums",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_xml_enums_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) = svc.build_xml_enums_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_xml_enums_response),
  )
}

fn xml_int_enums_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#XmlIntEnums",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_xml_int_enums_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_xml_int_enums_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_xml_int_enums_response),
  )
}

fn xml_lists_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#XmlLists",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_xml_lists_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) = svc.build_xml_lists_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_xml_lists_response),
  )
}

fn xml_maps_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#XmlMaps",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_xml_maps_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) = svc.build_xml_maps_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_xml_maps_response),
  )
}

fn xml_maps_xml_name_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#XmlMapsXmlName",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_xml_maps_xml_name_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_xml_maps_xml_name_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_xml_maps_xml_name_response),
  )
}

fn xml_map_with_xml_namespace_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#XmlMapWithXmlNamespace",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_xml_map_with_xml_namespace_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_xml_map_with_xml_namespace_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(
      svc.parse_xml_map_with_xml_namespace_response,
    ),
  )
}

fn xml_namespaces_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#XmlNamespaces",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_xml_namespaces_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_xml_namespaces_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_xml_namespaces_response),
  )
}

fn xml_timestamps_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#XmlTimestamps",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_xml_timestamps_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_xml_timestamps_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_xml_timestamps_response),
  )
}

fn xml_unions_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#XmlUnions",
    build_request: fn(params) {
      let raw = case params {
        "" -> "{}"
        other -> other
      }
      case svc.decode_xml_unions_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_xml_unions_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
    parse_response: response_parser(svc.parse_xml_unions_response),
  )
}

fn complex_error_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#ComplexError",
    build_request: fn(_params) {
      Error("error-shape dispatcher has no request side")
    },
    parse_response: response_parser(svc.parse_complex_error_response),
  )
}

fn invalid_greeting_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.restxml#InvalidGreeting",
    build_request: fn(_params) {
      Error("error-shape dispatcher has no request side")
    },
    parse_response: response_parser(svc.parse_invalid_greeting_response),
  )
}

fn response_parser(
  parser: fn(Int, _, BitArray) -> Result(_, String),
) -> fn(ParsedResponseInput) -> Result(dispatch.ParsedResponse, String) {
  fn(input: ParsedResponseInput) {
    case parser(input.code, input.headers, input.body) {
      Ok(_) -> Ok(ParsedOutput(json: "{}"))
      Error(e) -> Error(e)
    }
  }
}
