//// Auto-generated by codegen/dispatcher.gleam for rpcv2cbor.
//// DO NOT EDIT manually — re-run `./scripts/regen.sh` after
//// regenerating the service module.

import aws/services/protocoltests/rpcv2cbor as svc
import protocol_tests/dispatch.{
  type Dispatcher, type ParsedResponseInput, type Registry, BuiltRequest,
  Dispatcher, ParsedOutput,
}

pub fn register_all(registry: Registry) -> Registry {
  registry
  |> dispatch.register(non_query_compatible_operation_dispatcher())
  |> dispatch.register(query_compatible_operation_dispatcher())
  |> dispatch.register(custom_code_error_dispatcher())
  |> dispatch.register(no_custom_code_error_dispatcher())
}

fn non_query_compatible_operation_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.rpcv2cbor#NonQueryCompatibleOperation",
    build_request: fn(_params) {
      let #(method, uri, headers, body) =
        svc.build_non_query_compatible_operation_request(
          svc.NonQueryCompatibleOperationInput,
        )
      Ok(BuiltRequest(method: method, uri: uri, headers: headers, body: body))
    },
    parse_response: response_parser(
      svc.parse_non_query_compatible_operation_response,
    ),
  )
}

fn query_compatible_operation_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.rpcv2cbor#QueryCompatibleOperation",
    build_request: fn(_params) {
      let #(method, uri, headers, body) =
        svc.build_query_compatible_operation_request(
          svc.QueryCompatibleOperationInput,
        )
      Ok(BuiltRequest(method: method, uri: uri, headers: headers, body: body))
    },
    parse_response: response_parser(
      svc.parse_query_compatible_operation_response,
    ),
  )
}

fn custom_code_error_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.rpcv2cbor#CustomCodeError",
    build_request: fn(_params) {
      Error("error-shape dispatcher has no request side")
    },
    parse_response: response_parser(svc.parse_custom_code_error_response),
  )
}

fn no_custom_code_error_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: "aws.protocoltests.rpcv2cbor#NoCustomCodeError",
    build_request: fn(_params) {
      Error("error-shape dispatcher has no request side")
    },
    parse_response: response_parser(svc.parse_no_custom_code_error_response),
  )
}

fn response_parser(
  parser: fn(Int, _, BitArray) -> Result(_, String),
) -> fn(ParsedResponseInput) -> Result(dispatch.ParsedResponse, String) {
  fn(input: ParsedResponseInput) {
    case parser(input.code, input.headers, input.body) {
      Ok(_) -> Ok(ParsedOutput(json: "{}"))
      Error(e) -> Error(e)
    }
  }
}
