#!/usr/bin/env python3
"""Emit a per-protocol dispatchers Gleam file from a generated service module.

Reads `src/aws/services/protocoltests/<module>.gleam`, finds every
`build_<snake>_request` + `parse_<snake>_response` pair AND every
`decode_<snake>_input` (used to lift params JSON into the typed input
record), and writes the matching `register_all(registry)` chain to
`test/protocol_tests/<protocol>_dispatchers.gleam`.

This bridges the generator output to the test runner's dispatch
registry without leaking test-only types back into the generated
service module.

Run after `gleam run -m aws_codegen -- ...`.
"""

import argparse, re, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--protocol', required=True)
    ap.add_argument('--service-module', required=True)
    ap.add_argument('--namespace', required=True)
    args = ap.parse_args()

    in_path = ROOT / 'src' / (args.service_module + '.gleam')
    if not in_path.exists():
        sys.exit(f"not found: {in_path}")
    text = in_path.read_text()

    # Pair each `build_<snake>_request` with the Input type it takes —
    # this is the only reliable mapping, since the emitter also produces
    # named Input types in the preamble for nested model shapes and
    # those interleave with per-op synthesis in an unpredictable order.
    build_re = re.compile(
        r'pub fn build_(\w+)_request\(\s*(?:_input|input):\s*(\w+),',
        re.M,
    )
    pairs = build_re.findall(text)
    if not pairs:
        sys.exit(f"no build_*_request functions found in {in_path}")

    # Whether the module exposes decode_<snake>_input (typed input) or
    # only the singleton (empty input).
    typed_inputs = set(re.findall(r'pub fn decode_(\w+)_input\b', text))

    ops_data = []
    for snake, input_type in pairs:
        # The Smithy operation's local PascalCase name = the snake name
        # we used to derive build_*_request. Convert snake → PascalCase.
        op_pascal = ''.join(p.capitalize() for p in snake.split('_'))
        op_id = f"{args.namespace}#{op_pascal}"
        has_decode = snake in typed_inputs
        ops_data.append((snake, input_type, op_id, has_decode))

    out_path = ROOT / 'test' / 'protocol_tests' / f'{args.protocol}_dispatchers.gleam'
    lines = []
    lines.append(f'//// Auto-generated by scripts/emit-dispatchers.py for {args.protocol}.')
    lines.append('//// DO NOT EDIT manually — re-run the script after regenerating the')
    lines.append('//// service module.')
    lines.append('')
    lines.append(f'import {args.service_module} as svc')
    lines.append('import protocol_tests/dispatch.{')
    lines.append('  type Dispatcher, type ParsedResponseInput, type Registry,')
    lines.append('  BuiltRequest, Dispatcher, ParsedOutput,')
    lines.append('}')
    lines.append('')
    lines.append('pub fn register_all(registry: Registry) -> Registry {')
    lines.append('  registry')
    for snake, _input_type, _op_id, _has_decode in ops_data:
        lines.append(f'  |> dispatch.register({snake}_dispatcher())')
    lines.append('}')
    lines.append('')
    for snake, input_type, op_id, has_decode in ops_data:
        lines.append(f'fn {snake}_dispatcher() -> Dispatcher {{')
        lines.append(f'  Dispatcher(')
        lines.append(f'    operation_id: "{op_id}",')
        lines.append(f'    build_request: fn(params) {{')
        if has_decode:
            # Typed input: decode params JSON, fall back to "{}" when
            # the case has no params block.
            lines.append(f'      let raw = case params {{')
            lines.append(f'        "" -> "{{}}"')
            lines.append(f'        other -> other')
            lines.append(f'      }}')
            lines.append(f'      case svc.decode_{snake}_input(raw) {{')
            lines.append(f'        Ok(input) -> {{')
            lines.append(f'          let #(method, uri, headers, body) =')
            lines.append(f'            svc.build_{snake}_request(input)')
            lines.append(f'          Ok(BuiltRequest(method:, uri:, headers:, body:))')
            lines.append(f'        }}')
            lines.append(f'        Error(reason) -> Error(reason)')
            lines.append(f'      }}')
        else:
            lines.append(f'      let _ = params')
            lines.append(f'      let #(method, uri, headers, body) =')
            lines.append(f'        svc.build_{snake}_request(svc.{input_type})')
            lines.append(f'      Ok(BuiltRequest(method:, uri:, headers:, body:))')
        lines.append(f'    }},')
        lines.append(f'    parse_response: response_parser(svc.parse_{snake}_response),')
        lines.append(f'  )')
        lines.append(f'}}')
        lines.append('')
    lines.append('fn response_parser(')
    lines.append('  parser: fn(Int, _, BitArray) -> Result(_, String),')
    lines.append(') -> fn(ParsedResponseInput) -> Result(dispatch.ParsedResponse, String) {')
    lines.append('  fn(input: ParsedResponseInput) {')
    lines.append('    case parser(input.code, input.headers, input.body) {')
    lines.append('      Ok(_) -> Ok(ParsedOutput(json: "{}"))')
    lines.append('      Error(e) -> Error(e)')
    lines.append('    }')
    lines.append('  }')
    lines.append('}')
    out_path.write_text('\n'.join(lines) + '\n')
    print(f"wrote {out_path} ({len(ops_data)} dispatchers, {sum(1 for _,_,_,t in ops_data if t)} typed)")

if __name__ == '__main__':
    main()
