#!/usr/bin/env python3
"""Emit a per-protocol dispatchers Gleam file from a generated service module.

Reads `src/aws/services/protocoltests/<module>.gleam`, finds every
`build_<snake>_request` + `parse_<snake>_response` pair, and writes the
matching `register_all(registry)` chain to
`test/protocol_tests/<protocol>_dispatchers.gleam`.

This bridges the generator output (which is service-only and protocol-
agnostic) to the test runner's dispatch registry — without leaking the
test-only types back into the generated service module.

Run after `gleam run -m aws_codegen -- ...`.
"""

import argparse, re, sys, os, pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--protocol', required=True,
                    help='e.g. awsjson10, awsjson11, restjson1, restxml, awsquery, ec2query')
    ap.add_argument('--service-module', required=True,
                    help='e.g. aws/services/protocoltests/restjson1')
    ap.add_argument('--namespace', required=True,
                    help='operation-id prefix e.g. aws.protocoltests.restjson')
    args = ap.parse_args()

    in_path = ROOT / 'src' / (args.service_module + '.gleam')
    if not in_path.exists():
        sys.exit(f"not found: {in_path}")
    text = in_path.read_text()

    # Find every operation by its build_<snake>_request signature.
    # Match the type name we'll need from the same module.
    ops = []
    pattern = re.compile(
        r'pub fn build_(\w+)_request\([^)]*\)',
        re.M,
    )
    for m in pattern.finditer(text):
        snake = m.group(1)
        # Convert snake → PascalCase for the type name
        pascal = ''.join(p.capitalize() for p in snake.split('_'))
        # Special: capitalize HTTP-style acronyms? smithy operation names are
        # already Pascal so we round-trip if we kept casing — but pascal_to_snake
        # is lossy. We need an alternate map. For now use a regex on the
        # generated source for the type name.
        type_match = re.search(
            rf'pub type (\w+Input) \{{\s*\1\b',
            text,
        )
        ops.append(snake)

    # Build a set of (snake, PascalInput, PascalOutput, operation_id) by
    # scanning Input types AND the comment lines.
    type_re = re.compile(r'pub type (\w+)Input \{\s*\1Input', re.M)
    types = type_re.findall(text)

    # Each Input type corresponds to one op in document order.
    # And each op has a one-line "build_<snake>_request" signature in the same order.
    # Pair them up.
    snakes = pattern.findall(text)
    if len(snakes) != len(types):
        sys.exit(f"mismatch: {len(snakes)} build fns vs {len(types)} types")

    ops_data = []
    for snake, pascal in zip(snakes, types):
        # Operation id = namespace + '#' + pascal
        ops_data.append((snake, pascal, f"{args.namespace}#{pascal}"))

    # Generate the dispatchers file.
    out_path = ROOT / 'test' / 'protocol_tests' / f'{args.protocol}_dispatchers.gleam'
    lines = []
    lines.append(f'//// Auto-generated by scripts/emit-dispatchers.py for {args.protocol}.')
    lines.append('//// DO NOT EDIT manually — re-run the script after regenerating the')
    lines.append('//// service module.')
    lines.append('')
    lines.append(f'import {args.service_module.replace("/","/")} as svc')
    lines.append('import protocol_tests/dispatch.{')
    lines.append('  type Dispatcher, type ParsedResponseInput, type Registry,')
    lines.append('  BuiltRequest, Dispatcher, ParsedOutput,')
    lines.append('}')
    lines.append('')
    lines.append('pub fn register_all(registry: Registry) -> Registry {')
    lines.append('  registry')
    for snake, pascal, op_id in ops_data:
        lines.append(f'  |> dispatch.register({snake}_dispatcher())')
    lines.append('}')
    lines.append('')
    for snake, pascal, op_id in ops_data:
        lines.append(f'fn {snake}_dispatcher() -> Dispatcher {{')
        lines.append(f'  Dispatcher(')
        lines.append(f'    operation_id: "{op_id}",')
        lines.append(f'    build_request: fn(_params) {{')
        lines.append(f'      let #(method, uri, headers, body) =')
        lines.append(f'        svc.build_{snake}_request(svc.{pascal}Input)')
        lines.append(f'      Ok(BuiltRequest(method: method, uri: uri, headers: headers, body: body))')
        lines.append(f'    }},')
        lines.append(f'    parse_response: empty_response_parser(svc.parse_{snake}_response),')
        lines.append(f'  )')
        lines.append(f'}}')
        lines.append('')
    lines.append('fn empty_response_parser(')
    lines.append('  parser: fn(Int, _, BitArray) -> Result(_, String),')
    lines.append(') -> fn(ParsedResponseInput) -> Result(dispatch.ParsedResponse, String) {')
    lines.append('  fn(input: ParsedResponseInput) {')
    lines.append('    case parser(input.code, input.headers, input.body) {')
    lines.append('      Ok(_) -> Ok(ParsedOutput(json: "{}"))')
    lines.append('      Error(e) -> Error(e)')
    lines.append('    }')
    lines.append('  }')
    lines.append('}')
    out_path.write_text('\n'.join(lines) + '\n')
    print(f"wrote {out_path} ({len(ops_data)} dispatchers)")

if __name__ == '__main__':
    main()
