//// Emit a `<protocol>_dispatchers.gleam` test-harness file from the
//// per-operation data the protocol emitters already carry. Replaces
//// `scripts/emit-dispatchers.py`, whose regex scrape over emitted
//// Gleam was both brittle (a renamed `input` parameter silently
//// changed the dispatcher shape) and required a separate Python
//// step in `scripts/regen.sh`.
////
//// The emitter populates `DispatcherSpec` for every operation; the
//// CLI only writes a dispatcher file when an output path is given,
//// so production-service emissions (real S3 / DynamoDB) skip the
//// dispatcher entirely.

import gleam/list
import gleam/string

/// What the dispatcher emitter needs to produce a single operation
/// stub. Carries the wire-side names of the helper functions the
/// emitter just wrote into the service module.
pub type DispatcherSpec {
  DispatcherSpec(
    /// Smithy operation ID — `<namespace>#<PascalName>`.
    op_id: String,
    /// Snake-cased operation name; matches `build_<snake>_request`,
    /// `parse_<snake>_response`, and (when `has_typed_input` is `True`)
    /// `decode_<snake>_input`.
    snake: String,
    /// Public input record type name in the service module. For Unit
    /// inputs this is the synthesised singleton (e.g.
    /// `EmptyInputAndEmptyOutputInput`).
    input_type: String,
    /// `True` when the input shape carries members and a
    /// `decode_<snake>_input` function exists. `False` for Unit-input
    /// operations where the dispatcher constructs the singleton
    /// directly.
    has_typed_input: Bool,
  )
}

/// Render the full dispatcher source for a protocol. `service_module`
/// is the Gleam-import path of the service module the dispatcher
/// references (e.g. `aws/services/protocoltests/json10`), `protocol_
/// label` is the slug used in the leading auto-generated header
/// comment (e.g. `awsjson10` so the file reads consistently with
/// the previous Python output).
pub fn render(
  protocol_label: String,
  service_module: String,
  specs: List(DispatcherSpec),
) -> String {
  let header =
    "//// Auto-generated by codegen/dispatcher.gleam for "
    <> protocol_label
    <> ".
//// DO NOT EDIT manually — re-run `./scripts/regen.sh` after
//// regenerating the service module.

import "
    <> service_module
    <> " as svc
import protocol_tests/dispatch.{
  type Dispatcher, type ParsedResponseInput, type Registry, BuiltRequest,
  Dispatcher, ParsedOutput,
}

"
  let register_block = "pub fn register_all(registry: Registry) -> Registry {
  registry" <> list.fold(specs, "", fn(acc, s) { acc <> "
  |> dispatch.register(" <> s.snake <> "_dispatcher())" }) <> "
}

"
  let dispatcher_fns =
    list.fold(specs, "", fn(acc, s) { acc <> emit_dispatcher_fn(s) <> "\n" })
  let tail =
    "fn response_parser(
  parser: fn(Int, _, BitArray) -> Result(_, String),
) -> fn(ParsedResponseInput) -> Result(dispatch.ParsedResponse, String) {
  fn(input: ParsedResponseInput) {
    case parser(input.code, input.headers, input.body) {
      Ok(_) -> Ok(ParsedOutput(json: \"{}\"))
      Error(e) -> Error(e)
    }
  }
}
"
  header <> register_block <> dispatcher_fns <> tail
}

fn emit_dispatcher_fn(s: DispatcherSpec) -> String {
  let body = case s.has_typed_input {
    True -> emit_typed_body(s.snake)
    False -> emit_singleton_body(s.snake, s.input_type)
  }
  "fn " <> s.snake <> "_dispatcher() -> Dispatcher {
  Dispatcher(
    operation_id: \"" <> s.op_id <> "\",
" <> body <> "    parse_response: response_parser(svc.parse_" <> s.snake <> "_response),
  )
}
"
}

fn emit_typed_body(snake: String) -> String {
  "    build_request: fn(params) {
      let raw = case params {
        \"\" -> \"{}\"
        other -> other
      }
      case svc.decode_" <> snake <> "_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_" <> snake <> "_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    },
"
}

fn emit_singleton_body(snake: String, input_type: String) -> String {
  "    build_request: fn(params) {
      let _ = params
      let #(method, uri, headers, body) =
        svc.build_" <> snake <> "_request(svc." <> input_type <> ")
      Ok(BuiltRequest(method:, uri:, headers:, body:))
    },
"
}

/// `aws.protocoltests.json10` → `awsjson10`, etc. Used by the CLI to
/// derive the dispatcher filename when the caller doesn't supply one.
/// Mapping is fixed because the protocol-test namespaces are.
pub fn label_for_namespace(namespace: String) -> Result(String, String) {
  case namespace {
    "aws.protocoltests.json10" -> Ok("awsjson10")
    "aws.protocoltests.json" -> Ok("awsjson11")
    "aws.protocoltests.restjson" -> Ok("restjson1")
    "aws.protocoltests.restxml" -> Ok("restxml")
    "aws.protocoltests.query" -> Ok("awsquery")
    "aws.protocoltests.ec2" -> Ok("ec2query")
    other -> Error("no dispatcher label registered for namespace " <> other)
  }
}

/// Pull the namespace out of a Smithy ID (the part before `#`).
pub fn namespace_of(service_id: String) -> Result(String, String) {
  case string.split_once(service_id, "#") {
    Ok(#(ns, _)) -> Ok(ns)
    Error(_) -> Error("malformed service id: " <> service_id)
  }
}
