//// Emit a `<protocol>_dispatchers.gleam` test-harness file from the
//// per-operation data the protocol emitters already carry. Replaces
//// `scripts/emit-dispatchers.py`, whose regex scrape over emitted
//// Gleam was both brittle (a renamed `input` parameter silently
//// changed the dispatcher shape) and required a separate Python
//// step in `scripts/regen.sh`.
////
//// Output is built end-to-end as `code.Code` AST nodes. The
//// per-op `build_request` callback body is still a `Raw` fragment
//// (it embeds operation-specific snake-cased function names and
//// looks closer to hand-written Gleam than to a tree of `Let` /
//// `Case` / `Call` nodes); everything around it — module doc,
//// imports, `register_all` chain, per-op `Dispatcher(...)`
//// construction with labelled args, `response_parser` helper —
//// flows through the AST. Pattern follows plan.md Pass 7.

import codegen/code.{
  type Code, Blank, Call, CodeNone, CodeSome, Fn, Ident, Labelled, Module,
  ModuleDocComment, Param, Raw, StrLit,
}
import gleam/list
import gleam/string

fn name_concat(parts: List(String)) -> String {
  string.concat(parts)
}

/// What the dispatcher emitter needs to produce a single operation
/// stub. Carries the wire-side names of the helper functions the
/// emitter just wrote into the service module.
pub type DispatcherSpec {
  DispatcherSpec(
    /// Smithy operation ID — `<namespace>#<PascalName>`.
    op_id: String,
    /// Snake-cased operation name; matches `build_<snake>_request`,
    /// `parse_<snake>_response`, and (when `has_typed_input` is `True`)
    /// `decode_<snake>_input`.
    snake: String,
    /// Public input record type name in the service module. For Unit
    /// inputs this is the synthesised singleton (e.g.
    /// `EmptyInputAndEmptyOutputInput`).
    input_type: String,
    /// `True` when the input shape carries members and a
    /// `decode_<snake>_input` function exists. `False` for Unit-input
    /// operations where the dispatcher constructs the singleton
    /// directly.
    has_typed_input: Bool,
  )
}

/// Render the full dispatcher source for a protocol. `service_module`
/// is the Gleam-import path of the service module the dispatcher
/// references (e.g. `aws/services/protocoltests/json10`),
/// `protocol_label` is the slug used in the leading auto-generated
/// header comment.
pub fn render(
  protocol_label: String,
  service_module: String,
  specs: List(DispatcherSpec),
) -> String {
  let preamble = [
    ModuleDocComment([
      name_concat([
        "Auto-generated by codegen/dispatcher.gleam for ",
        protocol_label,
        ".",
      ]),
      "DO NOT EDIT manually — re-run `./scripts/regen.sh` after",
      "regenerating the service module.",
    ]),
    Blank,
    code.Import(path: service_module, alias: CodeSome("svc"), unqualified: []),
    code.Import(path: "protocol_tests/dispatch", alias: CodeNone, unqualified: [
      "type Dispatcher", "type ParsedResponseInput", "type Registry",
      "BuiltRequest", "Dispatcher", "ParsedOutput",
    ]),
    Blank,
    register_all_fn(specs),
    Blank,
  ]
  let per_op =
    list.fold(specs, [], fn(acc, s) { [dispatcher_fn(s), Blank, ..acc] })
    |> list.reverse
  let tail = [response_parser_fn()]
  code.render(Module(items: list.append(list.append(preamble, per_op), tail)))
}

fn register_all_fn(specs: List(DispatcherSpec)) -> Code {
  // The `registry |> dispatch.register(...) |> ...` chain is the
  // one piece of dispatcher output that `gleam format` always
  // wraps idiomatically — emitting it through the AST would
  // duplicate the formatter's logic. Stays as `Raw` inside an
  // otherwise AST-built `Fn`.
  let pipe_body =
    string.concat([
      "registry",
      list.fold(specs, "", fn(acc, s) {
        name_concat([
          acc,
          "\n  |> dispatch.register(",
          s.snake,
          "_dispatcher())",
        ])
      }),
    ])
  Fn(
    public: True,
    name: "register_all",
    params: [Param(name: "registry", type_: "Registry")],
    return: CodeSome("Registry"),
    body: Raw(fragment: pipe_body),
  )
}

fn dispatcher_fn(s: DispatcherSpec) -> Code {
  let build_request_body = case s.has_typed_input {
    True -> typed_build_request(s.snake)
    False -> singleton_build_request(s.snake, s.input_type)
  }
  // `Dispatcher` is constructed with labelled args. Each label is
  // a `Labelled` node so the AST captures both the keyword and the
  // value; the value side is still `Raw` for the callback bodies
  // (which embed operation-specific symbol names) and an `Ident`
  // for the `parse_response` callsite.
  Fn(
    public: False,
    name: name_concat([s.snake, "_dispatcher"]),
    params: [],
    return: CodeSome("Dispatcher"),
    body: Call(Ident("Dispatcher"), [
      Labelled(label: "operation_id", value: StrLit(s.op_id)),
      Labelled(label: "build_request", value: Raw(fragment: build_request_body)),
      Labelled(
        label: "parse_response",
        value: Raw(
          fragment: name_concat([
            "response_parser(svc.parse_",
            s.snake,
            "_response)",
          ]),
        ),
      ),
    ]),
  )
}

fn typed_build_request(snake: String) -> String {
  name_concat([
    "fn(params) {
      let raw = case params {
        \"\" -> \"{}\"
        other -> other
      }
      case svc.decode_",
    snake,
    "_input(raw) {
        Ok(input) -> {
          let #(method, uri, headers, body) =
            svc.build_",
    snake,
    "_request(input)
          Ok(BuiltRequest(method:, uri:, headers:, body:))
        }
        Error(reason) -> Error(reason)
      }
    }",
  ])
}

fn singleton_build_request(snake: String, input_type: String) -> String {
  name_concat([
    "fn(params) {
      let _ = params
      let #(method, uri, headers, body) =
        svc.build_",
    snake,
    "_request(svc.",
    input_type,
    ")
      Ok(BuiltRequest(method:, uri:, headers:, body:))
    }",
  ])
}

fn response_parser_fn() -> Code {
  Fn(
    public: False,
    name: "response_parser",
    params: [
      Param(name: "parser", type_: "fn(Int, _, BitArray) -> Result(_, String)"),
    ],
    return: CodeSome(
      "fn(ParsedResponseInput) -> Result(dispatch.ParsedResponse, String)",
    ),
    body: Raw(
      fragment: "fn(input: ParsedResponseInput) {
    case parser(input.code, input.headers, input.body) {
      Ok(_) -> Ok(ParsedOutput(json: \"{}\"))
      Error(e) -> Error(e)
    }
  }",
    ),
  )
}

/// `aws.protocoltests.json10` → `awsjson10`, etc. Used by the CLI to
/// derive the dispatcher filename when the caller doesn't supply one.
/// Mapping is fixed because the protocol-test namespaces are.
pub fn label_for_namespace(namespace: String) -> Result(String, String) {
  case namespace {
    "aws.protocoltests.json10" -> Ok("awsjson10")
    "aws.protocoltests.json" -> Ok("awsjson11")
    "aws.protocoltests.restjson" -> Ok("restjson1")
    "aws.protocoltests.restxml" -> Ok("restxml")
    "aws.protocoltests.query" -> Ok("awsquery")
    "aws.protocoltests.ec2" -> Ok("ec2query")
    other ->
      Error(
        string.concat([
          "no dispatcher label registered for namespace ",
          other,
        ]),
      )
  }
}

/// Pull the namespace out of a Smithy ID (the part before `#`).
pub fn namespace_of(service_id: String) -> Result(String, String) {
  case string.split_once(service_id, "#") {
    Ok(#(ns, _)) -> Ok(ns)
    Error(_) -> Error(string.concat(["malformed service id: ", service_id]))
  }
}
