//// Emit a `<protocol>_dispatchers.gleam` test-harness file from the
//// per-operation data the protocol emitters already carry. Replaces
//// `scripts/emit-dispatchers.py`, whose regex scrape over emitted
//// Gleam was both brittle (a renamed `input` parameter silently
//// changed the dispatcher shape) and required a separate Python
//// step in `scripts/regen.sh`.
////
//// Output is built end-to-end as `code.Code` AST nodes: module doc,
//// imports, `register_all` chain, per-op `Dispatcher(...)`
//// construction with labelled args, request callbacks, and the
//// `response_parser` helper all flow through the AST.

import codegen/code.{
  type Code, Blank, Call, CodeNone, CodeSome, Fn, Ident, Labelled, Module,
  ModuleDocComment, Param, StrLit,
}
import gleam/list
import gleam/string

fn name_concat(parts: List(String)) -> String {
  string.concat(parts)
}

/// What the dispatcher emitter needs to produce a single operation
/// stub. Carries the wire-side names of the helper functions the
/// emitter just wrote into the service module.
pub type DispatcherSpec {
  DispatcherSpec(
    /// Smithy operation ID — `<namespace>#<PascalName>`. For error-shape
    /// dispatchers (`is_error_shape: True`) this is the error shape ID.
    op_id: String,
    /// Snake-cased operation name; matches `build_<snake>_request`,
    /// `parse_<snake>_response`, and (when `has_typed_input` is `True`)
    /// `decode_<snake>_input`.
    snake: String,
    /// Public input record type name in the service module. For Unit
    /// inputs this is the synthesised singleton (e.g.
    /// `EmptyInputAndEmptyOutputInput`). Unused for error-shape
    /// dispatchers.
    input_type: String,
    /// `True` when the input shape carries members and a
    /// `decode_<snake>_input` function exists. `False` for Unit-input
    /// operations where the dispatcher constructs the singleton
    /// directly.
    has_typed_input: Bool,
    /// `True` when this spec is for an error shape (used as the
    /// dispatch target for `smithy.test#httpResponseTests` on the
    /// error itself). The emitted dispatcher's `build_request`
    /// callback returns `Error` — the runner only invokes
    /// `parse_response` for error-shape lookups, so no request-side
    /// code is ever generated.
    is_error_shape: Bool,
  )
}

/// Render the full dispatcher source for a protocol. `service_module`
/// is the Gleam-import path of the service module the dispatcher
/// references (e.g. `aws/services/protocoltests/json10`),
/// `protocol_label` is the slug used in the leading auto-generated
/// header comment.
pub fn render(
  protocol_label: String,
  service_module: String,
  specs: List(DispatcherSpec),
) -> String {
  let preamble = [
    ModuleDocComment([
      name_concat([
        "Auto-generated by codegen/dispatcher.gleam for ",
        protocol_label,
        ".",
      ]),
      "DO NOT EDIT manually — re-run `./scripts/regen.sh` after",
      "regenerating the service module.",
    ]),
    Blank,
    code.Import(path: service_module, alias: CodeSome("svc"), unqualified: []),
    code.Import(path: "protocol_tests/dispatch", alias: CodeNone, unqualified: [
      "type Dispatcher", "type ParsedResponseInput", "type Registry",
      "BuiltRequest", "Dispatcher", "ParsedOutput",
    ]),
    Blank,
    register_all_fn(specs),
    Blank,
  ]
  let per_op =
    list.fold(specs, [], fn(acc, s) { [dispatcher_fn(s), Blank, ..acc] })
    |> list.reverse
  let tail = [response_parser_fn()]
  code.render(Module(items: list.append(list.append(preamble, per_op), tail)))
}

fn register_all_fn(specs: List(DispatcherSpec)) -> Code {
  let register_steps =
    list.map(specs, fn(s) {
      Call(Ident("dispatch.register"), [
        Call(Ident(name_concat([s.snake, "_dispatcher"])), []),
      ])
    })
  Fn(
    public: True,
    name: "register_all",
    params: [Param(name: "registry", type_: "Registry")],
    return: CodeSome("Registry"),
    body: code.Pipe(initial: Ident("registry"), steps: register_steps),
  )
}

fn dispatcher_fn(s: DispatcherSpec) -> Code {
  let build_request = case s.is_error_shape, s.has_typed_input {
    True, _ -> error_shape_build_request()
    False, True -> typed_build_request(s.snake)
    False, False -> singleton_build_request(s.snake, s.input_type)
  }
  Fn(
    public: False,
    name: name_concat([s.snake, "_dispatcher"]),
    params: [],
    return: CodeSome("Dispatcher"),
    body: Call(Ident("Dispatcher"), [
      Labelled(label: "operation_id", value: StrLit(s.op_id)),
      Labelled(label: "build_request", value: build_request),
      Labelled(
        label: "parse_response",
        value: Call(Ident("response_parser"), [
          Ident(name_concat(["svc.parse_", s.snake, "_response"])),
        ]),
      ),
    ]),
  )
}

fn typed_build_request(snake: String) -> Code {
  code.Lambda(
    params: ["params"],
    body: code.Block(items: [
      code.Let(
        name: "raw",
        value: code.Case(scrutinee: Ident("params"), branches: [
          code.Branch(pattern: "\"\"", body: StrLit("{}")),
          code.Branch(pattern: "other", body: Ident("other")),
        ]),
      ),
      code.Case(
        scrutinee: Call(Ident(name_concat(["svc.decode_", snake, "_input"])), [
          Ident("raw"),
        ]),
        branches: [
          code.Branch(
            pattern: "Ok(input)",
            body: built_request_ok(
              Call(Ident(name_concat(["svc.build_", snake, "_request"])), [
                Ident("input"),
              ]),
            ),
          ),
          code.Branch(
            pattern: "Error(reason)",
            body: Call(Ident("Error"), [Ident("reason")]),
          ),
        ],
      ),
    ]),
  )
}

fn singleton_build_request(snake: String, input_type: String) -> Code {
  code.Lambda(
    params: ["_params"],
    body: built_request_ok(
      Call(Ident(name_concat(["svc.build_", snake, "_request"])), [
        Ident(name_concat(["svc.", input_type])),
      ]),
    ),
  )
}

fn error_shape_build_request() -> Code {
  code.Lambda(
    params: ["_params"],
    body: Call(Ident("Error"), [
      StrLit("error-shape dispatcher has no request side"),
    ]),
  )
}

fn built_request_ok(build_call: Code) -> Code {
  code.Block(items: [
    code.Let(name: "#(method, uri, headers, body)", value: build_call),
    Call(Ident("Ok"), [
      Call(Ident("BuiltRequest"), [
        Labelled(label: "method", value: Ident("method")),
        Labelled(label: "uri", value: Ident("uri")),
        Labelled(label: "headers", value: Ident("headers")),
        Labelled(label: "body", value: Ident("body")),
      ]),
    ]),
  ])
}

fn response_parser_fn() -> Code {
  Fn(
    public: False,
    name: "response_parser",
    params: [
      Param(name: "parser", type_: "fn(Int, _, BitArray) -> Result(_, String)"),
    ],
    return: CodeSome(
      "fn(ParsedResponseInput) -> Result(dispatch.ParsedResponse, String)",
    ),
    body: code.TypedLambda(
      params: [Param(name: "input", type_: "ParsedResponseInput")],
      body: code.Case(
        scrutinee: Call(Ident("parser"), [
          Ident("input.code"),
          Ident("input.headers"),
          Ident("input.body"),
        ]),
        branches: [
          code.Branch(
            pattern: "Ok(_)",
            body: Call(Ident("Ok"), [
              Call(Ident("ParsedOutput"), [
                Labelled(label: "json", value: StrLit("{}")),
              ]),
            ]),
          ),
          code.Branch(
            pattern: "Error(e)",
            body: Call(Ident("Error"), [Ident("e")]),
          ),
        ],
      ),
    ),
  )
}

/// `aws.protocoltests.json10` → `awsjson10`, etc. Used by the CLI to
/// derive the dispatcher filename when the caller doesn't supply one.
/// Mapping is fixed because the protocol-test namespaces are.
pub fn label_for_namespace(namespace: String) -> Result(String, String) {
  case namespace {
    "aws.protocoltests.json10" -> Ok("awsjson10")
    "aws.protocoltests.json" -> Ok("awsjson11")
    "aws.protocoltests.restjson" -> Ok("restjson1")
    "aws.protocoltests.restxml" -> Ok("restxml")
    "aws.protocoltests.restxml.xmlns" -> Ok("restxml_with_namespace")
    "aws.protocoltests.query" -> Ok("awsquery")
    "aws.protocoltests.ec2" -> Ok("ec2query")
    "aws.protocoltests.rpcv2cbor" -> Ok("rpcv2cbor")
    other ->
      Error(
        string.concat([
          "no dispatcher label registered for namespace ",
          other,
        ]),
      )
  }
}

/// Pull the namespace out of a Smithy ID (the part before `#`).
pub fn namespace_of(service_id: String) -> Result(String, String) {
  case string.split_once(service_id, "#") {
    Ok(#(ns, _)) -> Ok(ns)
    Error(_) -> Error(string.concat(["malformed service id: ", service_id]))
  }
}
